### hub/auth — accounts: register, sign in, sign out, reset, verify.
###
### Generated by `void make auth`. Every page here stands on machinery
### that was already in the composition; what the generator wrote is
### the part that is the same in every application and different in
### none of the interesting ways.
###
### The accounts table below is **the application's**: void/auth-db
### reads it (`[:auth-db :users]` says which columns) and never writes
### to it, so registration and a password change are handlers here
### rather than something a plugin does behind them. The sign-up form
### is `schema/select` over that same entity plus the one field that is
### not a column, so a field added to the entity shows up in the form
### with its validation already attached (ADR-0008).
###
### **Reset and verification are one flow.** `auth/challenge!` mints a
### single-use code and hands it to whatever delivers (`:void/mail-auth`
### is one; a challenge nobody delivered is an error, ADR-0023 §7).
### There is **one** route that redeems, because a deliverer builds one
### URL — from `[:mail-auth :link-path]` — and which of the two the
### link was for is a claim that travelled on the challenge.
###
### **Nothing here says a word about CSRF.** `form/form` has been
### splicing the token slot since wave 1 and void/security binds it
### (ADR-0025) — the forms below carry a token because they are forms.
###
### Handlers are registered as symbols, so redefining one in the repl —
### or saving this file with `void dev` running — is live (ADR-0002).
(import void/core/plugin :as plugin)
(import void/core/schema :as schema)
(import void/db :as db)
(import void/auth :as auth)
(import void/auth/http :as auth-http)
(import void/http/router :as router)
(import void/http/ring :as ring)
(import void/http/wire :as wire)
(import void/html :as html)
(import void/html/form :as form)

# -- the declaration -----------------------------------------------------

(db/defentity User
  {:id [:int {:db/pk true :db/type "integer"}]
   :email [:string {:format :email :db/unique true :db/type "text"}]
   # a PHC string ($scrypt$ln=14,r=8,p=1$…), written by
   # `auth/hash-password` and read by void/auth-db's user store. It is
   # optional because an account that only ever arrives by link never
   # sets one — and void/auth's password strategy answers
   # :no-password for it after spending the time it would have spent
   # on a real check
   :password-hash [:optional [:string {:db/type "text"}]]
   :verified-at [:optional [:string {:db/type "text"}]]
   :created-at [:optional [:string {:db/type "text"}]]}
  :db/table "users")

# -- what the forms submit: projections of the entity, not copies --------

(def Registration
  ``The sign-up form. `schema/merge` composes the projection of the
  entity with the one field that has no place in it — the hash is what
  the table stores, and the plaintext exists for exactly the length of
  one request (ADR-0023 §4).``
  (schema/merge (schema/select User [:email])
                {:password [:string {:min 8 :max 200}]}))

(def Credentials
  "What the sign-in form submits."
  {:email [:string {:format :email}]
   :password [:string {:min 1 :max 200}]})

(def EmailOnly
  "What the \"mail me a reset link\" form submits — an address, and
  deliberately nothing else."
  {:email [:string {:format :email}]})

(def NewPassword
  "What the change-password form submits."
  {:password [:string {:min 8 :max 200}]})

# -- the account behind the identity -------------------------------------
#
# An identity is `{:subject "user:42" ...}` and nothing more
# (ADR-0023): void does not know what a user is, and these three
# functions are where this application says what one is.

(defn- now
  "An ISO-8601 UTC timestamp — text on every engine, which is what
  keeps the migration one file."
  []
  (def d (os/date (os/time) true))
  (string/format "%04d-%02d-%02dT%02d:%02d:%02dZ"
                 (d :year) (inc (d :month)) (inc (d :month-day))
                 (d :hours) (d :minutes) (d :seconds)))

(defn subject-string
  "The subject a record signs in as — `[:auth-db :users :subject-kind]`
  is the `user` half of it."
  [record]
  (string "user:" (record :id)))

(defn- find-by-email [email]
  (when email (db/one User {:where [:= :email email]})))

(defn- record-of
  "The row an identity points at, or nil."
  [id]
  (when id
    (when-let [n (scan-number (last (auth/subject-of (id :subject))))]
      (db/find User n))))

(defn current-record
  "The signed-in account as a row, or nil."
  []
  (record-of (auth/current-user)))

(defn send-verification!
  ``Ask somebody to confirm the address they registered with. The
  claim is what tells this challenge from a password reset when the
  link comes back — `challenge!` refuses if nobody delivered it, which
  is the failure you want: a page that spins forever with nothing in
  any log is the other one.``
  [record]
  (auth/challenge! (subject-string record)
                   {:to (record :email)
                    :claims {:purpose "verify"}}))

(defn- mark-verified! [id]
  (when-let [record (record-of id)]
    (unless (record :verified-at)
      (db/update! User (record :id) {:verified-at (now)}))))

(defn- next-path
  ``Where a redirected visitor was going. void/auth-http sends an
  unauthenticated request to `[:auth-http :login-path]` with `?next=`,
  and this reads it back — as **a path of this application and nothing
  else**. A `next` that starts a scheme or `//` is somebody else's
  origin, and following it is an open redirect with a sign-in page
  attached.``
  [req]
  (def raw (get (or (req :query) {}) "next"))
  (if (and raw (string/has-prefix? "/" raw) (not (string/has-prefix? "//" raw)))
    raw
    "/"))

# -- views ---------------------------------------------------------------
#
# Plain functions returning hiccup. `layout` is this module's own so
# that these pages render the moment they are generated; point it at
# the application's layout and delete this one.

(defn who-bar
  "Who is signed in, and the way out."
  []
  (if (auth/current-user)
    [:p {:class "who"}
     # the claim comes off the identity, which void/auth-http re-read
     # from the store on this request — no second query for a greeting
     "Signed in as " [:strong (or (auth/claim :email) (auth/subject))] " · "
     [:a {:href "/verify"} "Your address"] " "
     (form/form {} {:action "/logout" :submit "Sign out"})]
    [:p {:class "who"}
     [:a {:href "/login"} "Sign in"] " · "
     [:a {:href "/register"} "Create an account"]]))

(defn layout [content context]
  (html/html5 {:lang "en"}
    [:head
     [:meta {:charset "utf-8"}]
     [:meta {:name "viewport" :content "width=device-width, initial-scale=1"}]
     [:title "hub"]]
    [:body
     [:header (who-bar)]
     [:main content]]))

(defn- page [content]
  (html/page content {:layout layout}))

(defn- message-line [state]
  (when-let [m (get state :message)] [:p {:class "message"} m]))

(defn register-view
  ``The sign-up page. `state` is whatever the handler wants
  re-rendered: :values and :errors put an invalid submission back in
  the form annotated, :message is the one line it is allowed to say.``
  [&opt state]
  (default state {})
  [:div {:id "register"}
   [:h1 "Create an account"]
   (message-line state)
   (form/form Registration
     {:action "/register"
      :values (get state :values)
      :errors (get state :errors)
      :fields {:password {:type "password"}}
      :submit "Create an account"})
   [:p [:a {:href "/login"} "Already have an account?"]]])

(defn login-view
  "The sign-in page. :next is where the visitor was going before
  void/auth-http sent them here."
  [&opt state]
  (default state {})
  (def target (get state :next))
  [:div {:id "login"}
   [:h1 "Sign in"]
   (message-line state)
   (form/form Credentials
     {:action (if target (string "/login?next=" (wire/url-encode target)) "/login")
      :values (get state :values)
      :errors (get state :errors)
      :fields {:password {:type "password"}}
      :submit "Sign in"})
   [:p [:a {:href "/password/reset"} "Forgot your password?"] " · "
    [:a {:href "/register"} "Create an account"]]])

(defn reset-view
  "Ask for the address a reset link goes to."
  [&opt state]
  (default state {})
  [:div {:id "reset"}
   [:h1 "Reset your password"]
   (message-line state)
   (form/form EmailOnly
     {:action "/password/reset"
      :values (get state :values)
      :errors (get state :errors)
      :submit "Mail me a link"})])

(defn password-view
  "Set a new password — reached by following a reset link, or from an
  account page."
  [&opt state]
  (default state {})
  [:div {:id "password"}
   [:h1 "Choose a new password"]
   (message-line state)
   (form/form NewPassword
     {:action "/password"
      :values (get state :values)
      :errors (get state :errors)
      :fields {:password {:type "password"}}
      :submit "Save"})])

(defn verify-view
  "Where the confirmation link is asked for again — a link expires, and
  a flow with no way to send a second one is a dead end with a support
  ticket attached."
  [record]
  [:div {:id "verify"}
   [:h1 "Your address"]
   (if (get record :verified-at)
     [:p {:class "message"}
      (string (get record :email "") " is confirmed.")]
     [:div
      [:p "We sent a confirmation link to "
       [:strong (get record :email "")] "."]
      (form/form {} {:action "/verify" :submit "Send it again"})])])

(defn notice-view
  "One line, and nothing to fill in."
  [message]
  [:div {:id "notice"} [:p {:class "message"} message]])

# -- handlers ------------------------------------------------------------

(defn register-form
  "GET /register"
  [req]
  (page (register-view)))

(defn register
  ``POST /register — an account with a password.

  The sign-in that follows goes through the ordinary password path
  rather than trusting the row that was just written: one code path
  signs anybody in, so there is one place where that can be wrong.``
  [req]
  (def result (form/check Registration (req :form)))
  (def v (result :value))
  (def taken (and (empty? (result :errors)) (find-by-email (v :email))))
  (cond
    (not (empty? (result :errors)))
    (page (register-view {:values (req :form) :errors (result :errors)}))

    taken
    (page (register-view {:values (req :form)
                          :message "That address already has an account — sign in instead."}))

    (do
      (def created
        (db/insert! User
                    {:email (v :email)
                     :password-hash (auth/hash-password (v :password))
                     :created-at (now)}))
      (def check (auth/check-password (auth/user-store)
                                      {:email (v :email) :password (v :password)}))
      (auth-http/login! req (check :identity))
      (send-verification! created)
      (ring/redirect "/"))))

(defn login-form
  "GET /login — where [:auth-http :login-path] points."
  [req]
  (page (login-view {:next (get (or (req :query) {}) "next")})))

(defn login
  ``POST /login — the password path, and nothing else.

  Whatever went wrong, the page says the same thing:
  `check-password` distinguishes an unknown address from a wrong
  password and spends the same time on both (it hashes even when
  there is no account), and telling the visitor which it was would
  hand that distinction straight back.``
  [req]
  (def result (form/check Credentials (req :form)))
  (def check (when (empty? (result :errors))
               (auth/check-password (auth/user-store) (result :value))))
  (if-let [id (get check :identity)]
    (do
      (auth-http/login! req id)
      (ring/redirect (next-path req)))
    (page (login-view {:values (req :form)
                       :next (get (or (req :query) {}) "next")
                       :message "Those credentials do not match an account."}))))

(defn logout
  "POST /logout — drop the identity and rotate the session id."
  [req]
  (auth-http/logout! req)
  (ring/redirect "/"))

(defn reset-form
  "GET /password/reset"
  [req]
  (page (reset-view)))

(defn request-reset
  ``POST /password/reset — mail a link that signs them in long enough
  to choose a new password.

  **The answer is the same whether or not the address has an
  account.** A page that said "no such account" would be a way to ask
  this application who its users are, one address at a time — the
  same reasoning that makes `check-password` spend its time on an
  unknown login.``
  [req]
  (def result (form/check EmailOnly (req :form)))
  (def record (when (empty? (result :errors))
                (find-by-email (get-in result [:value :email]))))
  (when record
    (auth/challenge! (subject-string record)
                     {:to (record :email)
                      :claims {:purpose "reset"}}))
  (page (reset-view
          {:values (req :form)
           :message (if (empty? (result :errors))
                      "If that address has an account, a link is on its way."
                      "That does not look like an email address.")})))

(defn link
  ``GET /auth/link?h=&c= — the one path a letter points at
  ([:mail-auth :link-path]), for both challenges.

  `redeem!` takes the challenge out of the store *before* it checks
  the code (ADR-0023 §7), so a link works once and a wrong one is
  spent: the visitor asks for another, which costs them a click and an
  attacker a full guess per try. What the link was for is a claim that
  travelled on the challenge — no second table, and no second route.``
  [req]
  (def query (or (req :query) {}))
  (if-let [id (auth/redeem! (get query "h") (get query "c"))]
    (do
      (auth-http/login! req id)
      (if (= "reset" (get-in id [:claims :purpose]))
        (ring/redirect "/password/edit")
        (do
          (mark-verified! id)
          (ring/redirect "/"))))
    (page (login-view
            {:message "That link has expired or has already been used."}))))

(defn password-form
  "GET /password/edit"
  [req]
  (page (password-view)))

(defn update-password
  "POST /password — the route is :required, so there is somebody to
  change the password of."
  [req]
  (def result (form/check NewPassword (req :form)))
  (def record (current-record))
  (if (or (not (empty? (result :errors))) (nil? record))
    (page (password-view {:values (req :form) :errors (result :errors)}))
    (do
      (db/update! User (record :id)
                  {:password-hash (auth/hash-password (get-in result [:value :password]))})
      (page (notice-view "Your password has been changed.")))))

(defn verify-form
  "GET /verify"
  [req]
  (page (verify-view (current-record))))

(defn resend-verification
  "POST /verify — another confirmation link for the signed-in account.
  A confirmed address does not get one: the link signs whoever holds
  it in, and there is no reason to keep minting those."
  [req]
  (when-let [record (current-record)]
    (unless (record :verified-at)
      (send-verification! record)))
  (page (notice-view "A confirmation link is on its way.")))

# -- routes --------------------------------------------------------------
#
# Every route says what access it needs rather than leaning on
# [:auth-http :default]: the default is :public, an application that
# flips it to :required has taken a deny-by-default posture on purpose,
# and these twelve routes have to keep meaning the same thing under
# both. The names are also what a policy asks about (ADR-0029) — one
# name, read by more than one thing.

(router/defroutes :hub/auth-routes
  (GET "/register" register-form {:name :auth/register-form
                                  :void.auth/access :public})
  (POST "/register" register {:name :auth/register
                              :void.auth/access :public})
  (GET "/login" login-form {:name :auth/login-form
                            :void.auth/access :public})
  (POST "/login" login {:name :auth/login
                        :void.auth/access :public})
  (POST "/logout" logout {:name :auth/logout
                          :void.auth/access :public})
  (GET "/password/reset" reset-form {:name :auth/reset-form
                                     :void.auth/access :public})
  (POST "/password/reset" request-reset {:name :auth/reset-request
                                         :void.auth/access :public})
  # a GET that signs somebody in is safe here for the reason a password
  # POST is: the credential is in the URL and it is single-use
  (GET "/auth/link" link {:name :auth/link :void.auth/access :public})
  (GET "/password/edit" password-form {:name :auth/password-form
                                       :void.auth/access :required})
  (POST "/password" update-password {:name :auth/password-update
                                     :void.auth/access :required})
  (GET "/verify" verify-form {:name :auth/verify-form
                              :void.auth/access :required})
  (POST "/verify" resend-verification {:name :auth/verify-resend
                                       :void.auth/access :required}))

(plugin/defplugin hub/auth
  :doc "User accounts: register, sign in, sign out, password reset and address verification, over void/auth."
  :version "0.1.0"
  :requires {:void/http ">=0.0.1" :void/html ">=0.0.1" :void/db ">=0.0.1"
             :void/auth ">=0.0.1" :void/auth-http ">=0.0.1"
             :void/auth-db ">=0.0.1"})
