### users — generated by `void make auth user`.
###
### Two owners, one file. `users` is the application's: void/auth-db
### *reads* it (`[:auth-db :users]` says which columns) and never writes
### to it, which is why registration and a password change are handlers in
### auth.janet. The other two tables are void's own — API-token digests
### and single-use one-time codes — and void/auth-db ships their DDL as
### data rather than as a migration of its own, because a migration
### timeline belongs to the application.
###
### What a step returns is executed: void/db/builder compiles the
### statements for whichever engine is running, which is what keeps one
### migration file portable. Apply it with `void db migrate`.
(import void/auth/db :as auth-db)

(defn up
  {:params [] :ret [{:keyword :any}]}
  "The users table this application owns, plus the two void/auth-db
  ships as data."
  []
  [{:create-table "users"
    :columns [[:id :serial {:primary-key true}]
              [:email :text {:null false :unique true}]
              # a PHC string: the algorithm and its cost travel inside the
              # value, so raising the cost later is a config change rather
              # than a migration nobody can write. Nullable — an account
              # that only arrives by link has none
              [:password-hash :text]
              # text on both engines, so a row reads the same on either
              [:verified-at :text]
              [:created-at :text]]}
   ;(auth-db/tables)])

(defn down
  {:params [] :ret [{:keyword :any}]}
  "Drop void/auth-db's two tables and this application's own."
  []
  [;(auth-db/drop-tables)
   {:drop-table "users"}])
