### The accounts scaffold — generated by `void make auth`.
###
### Every flow driven the way a browser drives it: test/inject
### (ADR-0017) runs a request through the whole chain — the session,
### the CSRF check, the strategy chain, the route table — without
### opening a socket, so what passes here is what a browser gets.
###
### **The composition is written out** rather than read from
### main.janet, so that this suite runs the moment it is generated —
### before those plugins have been added there. Once they have, replace
### the list with main.janet's and the suite follows the application.
###
### **Delivery is a plugin of this file's own.** `auth/challenge!`
### refuses a challenge nobody delivered (ADR-0023 §7); in production
### :void/mail-auth is what delivers, and here it is five lines that
### keep the code where an assertion can read it — which is how the
### reset and the verification are proven without a mailbox.
(import void/core/plugin :as plugin)
(import void/core/log :as log)
(import void/test :as test)
(import void/db :as db)
# importing a plugin's module is what registers its manifest, which is
# what makes a keyword entry in :plugins below resolvable. The module
# under test imports void/auth and void/auth-http itself; these four it
# does not name, and they are in the composition all the same
(import void/crypto)
(import void/auth/db)
(import void/security)
(import void/db-sqlite)
(import ../auth :as accounts)

# -- the deliverer -------------------------------------------------------

(def delivered
  "Every challenge this suite caused, newest last."
  @[])

(def capture
  (plugin/manifest 'test/capture-challenges
    :doc "Keeps magic links where an assertion can read them."
    :contributes {:void.auth/deliver
                  [{:name :test/capture
                    :fn (fn capture [payload]
                          (array/push delivered payload)
                          true)}]}))

# -- the composition -----------------------------------------------------

(def sqlite-path
  (string (or (os/getenv "TMPDIR") "/tmp")
          "/hub-auth-test-" (os/time) ".sqlite3"))

(def plugins
  [:void/http :void/html
   :void/db :void/db-sqlite
   # every hash and every code comes from void/crypto (ADR-0022): this
   # composition hashes nothing itself
   :void/crypto :void/auth :void/auth-http :void/auth-db
   # the CSRF token the forms below carry without asking (ADR-0025)
   :void/security
   capture
   :hub/auth])

(def config
  {:env @{}
   :cli {:db {:migrations {:dir "db/migrations"}}
         :db-sqlite {:path sqlite-path}
         :http {:session {:enabled true}}
         # three interfaces have two implementations each — the memory
         # stores void/auth ships and the database ones void/auth-db
         # does — and the kernel refuses to guess (ADR-0030)
         :void/auth-user-store {:impl :auth.db/users}
         :void/auth-token-store {:impl :auth.db/tokens}
         :void/auth-challenge-store {:impl :auth.db/challenges}
         :auth-db {:users {:table "users"
                           :subject-kind "user"
                           :email-column "email"
                           :password-column "password_hash"
                           # on the identity, so a page can greet
                           # somebody without a second query
                           :claims-columns ["email"]}}
         :auth-http {:unauthenticated :redirect :login-path "/login"}
         # what the configured hasher costs is pinned in void/crypto;
         # this suite signs in a dozen times and does not need it
         :auth {:scrypt {:ln 10}}
         :crypto {:kdf {:in-thread false}}}})

# -- helpers -------------------------------------------------------------

(defn- text [resp] (test/text resp))

(defn- token-of
  "The CSRF token out of a rendered form — no page below asked for one."
  [resp]
  (first (peg/match ~(* (thru `name="_csrf" value="`) (<- (to `"`))) (text resp))))

(defn- message-of
  "The one line a page is allowed to say."
  [resp]
  (first (peg/match ~(* (thru `class="message">`) (<- (to "<"))) (text resp))))

(defn- token-for [client uri]
  (or (token-of (test/inject client {:uri uri}))
      (errorf "no CSRF token on %s" uri)))

(defn- link-of [challenge]
  (string "/auth/link?h=" (challenge :handle) "&c=" (challenge :code)))

(log/set-sinks! [(fn [_])])

(test/with-http [c {:plugins plugins
                    :profile :test
                    :config config
                    :only [:http/kernel :crypto/lib :auth/registry]}]
  (db/migrate-up! {:dir "db/migrations"})

  # -- registration ------------------------------------------------------

  (def form-page (test/inject c {:uri "/register"}))
  (assert (= 200 (form-page :status)) "the sign-up page renders")
  (assert (token-of form-page)
          "and carries a CSRF token nobody wrote a line for: form/form splices the slot, void/security binds it")

  (def registered
    (test/inject c {:uri "/register"
                    :headers {"x-csrf-token" (token-of form-page)}
                    :form {:email "ada@example.com"
                           :password "correct horse battery"}}))
  (assert (= 302 (registered :status)) "registering signs the visitor in")

  (def ada (db/one accounts/User {:where [:= :email "ada@example.com"]}))
  (assert ada "the account is a row in users")
  (assert (not (string/find "correct horse" (ada :password-hash)))
          "and the column holds a hash, not the password")
  (assert (string/has-prefix? "$" (ada :password-hash))
          "a PHC string: the algorithm and its cost travel inside the value")

  (def taken
    (test/inject (test/client (c :boot))
                 {:uri "/register"
                  :form {:email "ada@example.com"
                         :password "another password"}}))
  (assert (string/find "already has an account" (text taken))
          "a second account for the same address is refused, and says so")
  (assert (= 1 (db/count accounts/User)))

  # -- verifying the address ---------------------------------------------

  (assert (= 1 (length delivered))
          "registering asks the visitor to confirm their address — and challenge! would have raised if nobody delivered it")
  (assert (= "verify" (get-in (last delivered) [:claims :purpose]))
          "the claim is what tells this challenge from a reset")
  (assert (= "ada@example.com" ((last delivered) :to)))
  (assert (not (ada :verified-at)) "not verified until the link is followed")

  # a link expires in fifteen minutes; a flow with no second one is a
  # dead end with a support ticket attached
  (assert (string/find "We sent a confirmation link"
                       (text (test/inject c {:uri "/verify"}))))
  (assert (= 200 ((test/inject c {:method :post :uri "/verify"
                                  :headers {"x-csrf-token" (token-for c "/password/edit")}})
                  :status)))
  (assert (= 2 (length delivered)) "and asking again sends another")

  (def verification (last delivered))
  (assert (= 302 ((test/inject c {:uri (link-of verification)}) :status)))
  (assert ((db/find accounts/User (ada :id)) :verified-at)
          "following the link is what marks the address verified")

  (def replayed (test/inject (test/client (c :boot))
                             {:uri (link-of verification)}))
  (assert (string/find "expired or has already been used" (text replayed))
          "a link works once: redeem takes the challenge out of the store before it checks the code")

  (assert (string/find "is confirmed" (text (test/inject c {:uri "/verify"}))))
  (array/clear delivered)
  (assert (= 200 ((test/inject c {:method :post :uri "/verify"
                                  :headers {"x-csrf-token" (token-for c "/password/edit")}})
                  :status)))
  (assert (empty? delivered)
          "and a confirmed address stops minting links that sign whoever holds them in")

  # -- signing out, and back in ------------------------------------------

  (assert (= 302 ((test/inject c {:method :post :uri "/logout"
                                  :headers {"x-csrf-token" (token-for c "/login")}})
                  :status)))

  (def anon-token (token-for c "/login"))
  (defn- sign-in [email password]
    (test/inject c {:uri "/login"
                    :headers {"x-csrf-token" anon-token}
                    :form {:email email :password password}}))

  (def wrong (sign-in "ada@example.com" "not it"))
  (def unknown (sign-in "nobody@example.com" "not it"))
  (assert (= (wrong :status) (unknown :status)))
  (assert (= (message-of wrong) (message-of unknown))
          "a wrong password and an unknown address say exactly the same thing — telling them apart is a user-enumeration API, and check-password spends the same time on both")
  (each said ["no such" "unknown" "wrong password" "not registered"]
    (assert (not (string/find said (string/ascii-lower (text unknown))))
            (string "and the page does not say " said)))

  (assert (= 302 ((sign-in "ada@example.com" "correct horse battery") :status))
          "the right password signs in")

  # -- CSRF ---------------------------------------------------------------
  #
  # The credential rides on a cookie, which is exactly when CSRF
  # applies (ADR-0025 §1).

  (assert (= 403 ((test/inject c {:uri "/password"
                                  :form {:password "a password from nowhere"}})
                  :status))
          "a signed-in POST without the token is refused before the handler runs")

  # -- what :void.auth/access :required means ------------------------------

  (def anon (test/client (c :boot)))
  (def redirected (test/inject anon {:uri "/password/edit"}))
  (assert (= 302 (redirected :status))
          "an unauthenticated request to a protected route goes to the sign-in page, because this composition said :redirect")
  (assert (string/has-prefix? "/login?next=" (get-in redirected [:headers "location"]))
          "carrying where it was going")

  # -- the reset ----------------------------------------------------------

  (array/clear delivered)
  (def visitor (test/client (c :boot)))
  (def asked
    (test/inject visitor {:uri "/password/reset"
                          :headers {"x-csrf-token" (token-for visitor "/password/reset")}
                          :form {:email "ada@example.com"}}))
  (assert (string/find "on its way" (text asked)))
  (assert (= 1 (length delivered)))
  (def reset (last delivered))
  (assert (= "reset" (get-in reset [:claims :purpose])))

  (def landed (test/inject visitor {:uri (link-of reset)}))
  (assert (= "/password/edit" (get-in landed [:headers "location"]))
          "the link signs them in and lands on the form for a new password")

  (def edit (test/inject visitor {:uri "/password/edit"}))
  (assert (= 200 (edit :status)))
  (assert (= 200 ((test/inject visitor {:uri "/password"
                                        :headers {"x-csrf-token" (token-of edit)}
                                        :form {:password "a longer new password"}})
                  :status)))

  (def after (test/client (c :boot)))
  (defn- try-login [password]
    (test/inject after {:uri "/login"
                        :headers {"x-csrf-token" (token-for after "/login")}
                        :form {:email "ada@example.com" :password password}}))
  (assert (= 200 ((try-login "correct horse battery") :status))
          "the old password no longer signs anybody in")
  (assert (= 302 ((try-login "a longer new password") :status))
          "and the new one does")

  (array/clear delivered)
  (def stranger
    (test/inject visitor {:uri "/password/reset"
                          :headers {"x-csrf-token" (token-for visitor "/password/reset")}
                          :form {:email "nobody@example.com"}}))
  (assert (= (message-of asked) (message-of stranger))
          "an address with no account gets the same page — anything else is a way to ask this application who its users are")
  (assert (empty? delivered) "and nothing was sent to it"))

(log/set-sinks! nil)
(os/rm sqlite-path)

(print "auth-test ok")
