### void/cli/new — `void new NAME`: the project skeleton.
###
### The template is data — a tuple of {:path :render} entries, each
### :render a pure (fn [name] string) over the one hole this generator
### has; ./make is where a project overrides one. The generated project
### is the run!/CLI convention in miniature: main.janet defines `app` (the
### boot options the CLI reads) and a `main` that runs it, and app.janet
### is the application plugin contributing routes.
###
### The generated files also have to be *deployable*, and that is one
### line each in two of them: `declare-executable` in project.janet, so
### that `jpm build` produces the single binary, and a `main` that
### reads the profile at run time rather than in a value — because
### `jpm build` marshals this project's values into the executable, and
### a profile computed in `app` would be the profile of the machine
### that built it (docs/DEPLOY.md).

(import void/core :as core)
(import ./template)

(def project-template
  "project.janet: one dependency, and the executable target."
  ```
(declare-project
  :name "{{name}}"
  :description "A void application."
  # One dependency: void installs as a single bundle, and
  # everything it needs — spork, and the framework's own packages —
  # comes with it. It is pinned to the release this project was
  # generated by, so "jpm --local deps" reproduces the same void in
  # ./jpm_tree (which the void binary uses in preference to the tree
  # it was installed into); move the tag to upgrade.
  :dependencies [{:url "https://github.com/bondiano/void.git" :tag "{{void-tag}}"}])

# "jpm --local build" writes build/{{name}} — one file, no janet on the
# target and nothing to install (docs/DEPLOY.md). jpm marshals the
# "main" of the entry below into the executable and links the native
# modules it finds statically, which is why main.janet reads the
# profile at run time rather than into a value.
(declare-executable
  :name "{{name}}"
  :entry "main.janet"
  :install false)
```)

(def main-template
  "main.janet: the boot options, and the two ways to start them."
  ```
### {{name}} — entrypoint. Run the app with `void dev` (or
### `janet main.janet`); the void CLI (void routes, void repl, ...)
### reads the app binding below.
(import void/cli :as cli)
(import void/http)
(import void/html)
(import void/htmx)
(import void/dev)
(import ./app)

# void/dev is a dev-time plugin: it serves a repl and watches the tree,
# and it builds that repl's environment with `require` — which a single
# binary has no source tree to require from (docs/DEPLOY.md). So the
# production composition is this one without it, and dropping a plugin
# from a list is the whole of the change.
(defn plugins
  "The composition for a profile."
  [profile]
  (def all [:void/http :void/html :void/htmx :void/dev :{{name}}/app])
  (if (= :prod profile)
    (filter |(not= :void/dev $) all)
    all))

(def app
  ``Boot options — what (void/run! ...) starts and the void CLI reads.
  :plugins-for is the explicit contract both honor: the composition as
  a function of the profile, so `void dev --profile prod` and
  `VOID_PROFILE=prod janet main.janet` are the same application.``
  {:plugins-for plugins})

(defn main [& args]
  # The profile is read here rather than in `app` above: `jpm build`
  # marshals this file's values into the executable, so anything a
  # value computes is computed once, on the machine that built it.
  (def profile (keyword (or (os/getenv "VOID_PROFILE") "dev")))
  # cli/app-main runs the app when there are no arguments and is the
  # `void` binary when there are — so `./build/{{name}} db migrate`
  # works on a target with no janet and no source tree, against exactly
  # the composition inside this executable (docs/DEPLOY.md).
  (cli/app-main {:plugins (plugins profile) :profile profile} ;(drop 1 args)))
```)

(def app-template
  "app.janet: the application plugin — schema, views, routes."
  ```
### {{name}}/app — the application plugin: schema, views, routes.
### Handlers are registered as symbols (late binding): redefine one in
### the repl — or save this file with the watcher running — and the
### running app picks it up; route and metadata edits rebuild the
### table on the fly.
(import void/core/plugin :as plugin)
(import void/http/router :as router)
(import void/html :as html)
(import void/html/form :as form)
(import void/htmx/hx :as hx)

# -- schema: one source of truth for validation and form markup ----------

(def Entry
  "A guestbook entry — drives both form/check and form/form."
  {:name [:string {:min 1 :max 40}]
   :message [:string {:min 1 :max 400}]})

# -- state (in-memory until void/db lands in your :plugins) --------------

(def entries @[])

# -- views (plain functions returning hiccup) ----------------------------

(defn layout [content context]
  (html/html5
    [:head
     [:meta {:charset "utf-8"}]
     [:title "{{name}}"]
     [:script {:src "https://unpkg.com/htmx.org@4.0.0"}]]
    [:body [:main content]]))

(defn guestbook-view
  "The #guestbook fragment: schema-driven form plus the entries list.
  On an invalid submission the caller passes the raw values and the
  schema errors back in and the same markup re-renders annotated."
  [&opt values errors]
  [:div {:id "guestbook"}
   [:h1 "{{name}} guestbook"]
   (form/form Entry
     {:action "/entries"
      :values values
      :errors errors
      :fields {:message {:control :textarea}}
      :submit "Sign"
      :attrs (hx/post "/entries" :target "#guestbook" :swap :outer-html)})
   [:ul {:class "entries"}
    (if (empty? entries)
      [:li {:class "empty"} "No entries yet — sign the book."]
      (seq [e :in (reverse entries)]
        [:li [:strong (e :name)] ": " (e :message)]))]])

# -- handlers ------------------------------------------------------------

(defn home
  "GET / — the full page."
  [req]
  (html/page (guestbook-view) {:layout layout}))

(defn create-entry
  "POST /entries — form/check validates and coerces against Entry;
  invalid input re-renders the fragment with per-field errors."
  [req]
  (def result (form/check Entry (req :form)))
  (if (empty? (result :errors))
    (do
      (array/push entries (result :value))
      (html/page (guestbook-view) {:layout layout}))
    (html/page (guestbook-view (req :form) (result :errors))
               {:layout layout})))

# -- routes --------------------------------------------------------------

# defroutes writes the :void.http/route-source contribution: handler
# symbols are quoted for you (late binding) and name their route.
(router/defroutes :{{name}}/routes
  (GET "/" home)
  # :void.htmx/partial — a swap into an element (HX-Request-Type:
  # partial) gets the bare fragment; a plain form POST still gets the
  # full page
  (POST "/entries" create-entry
        {:name :entries/create :void.htmx/partial true}))

(plugin/defplugin {{name}}/app
  :doc "{{name}} application plugin."
  :version "0.1.0"
  :requires {:void/http ">=0.0.1" :void/html ">=0.0.1" :void/htmx ">=0.0.1"})
```)

(def config-template
  "config/dev.janet: the file layer of the config chain."
  ```
# {{name}} :dev profile config layer (void/core/config: plugin
# defaults <- config files <- VOID_* env vars <- CLI overrides).
{:http {:port 8080}}
```)

(def prod-config-template
  "config/prod.janet: the profile a deploy runs, with its decisions
  named before they are made for you."
  ```
# {{name}} :prod profile config layer — what `VOID_PROFILE=prod
# ./build/{{name}}` reads on top of the plugin defaults
# (void/core/config: plugin defaults <- config files <- VOID_* env
# vars <- CLI overrides — every line here still loses to the
# environment, which is where per-machine values belong).
#
# main.janet drops :void/dev from the :prod composition, so there is
# no watcher and no netrepl behind this file.
{:http {# a server answers the network, not just this machine's
        # loopback — on a container or a VM this is what makes the
        # port reachable; behind a proxy on the same host, put it
        # back to "127.0.0.1"
        :host "0.0.0.0"
        # the environment spelling is VOID_HTTP__PORT=8080
        :port 8080}

 # :info keeps the access log and drops the debug chatter; in :prod
 # records go out as JDN lines a collector can parse
 :log {:level :info}}

# Decide before the first deploy — none of it is decided here yet:
#
#   * secrets: a plugin that signs (sessions, CSRF — :void/security)
#     refuses an ephemeral key in :prod; give it a secret *reference*
#     ({:secret "APP_SECRET_KEY"}) and put the value in the
#     environment, so the config tree holds a box that does not print
#   * more than one replica? say so — {:deploy {:shape :fleet}} — and
#     `void deploy check` will name every store that cannot be shared
#   * the guestbook itself lives in this process's memory: the first
#     real deploy wants :void/db and a driver in main.janet
```)

(def compose-template
  "docker-compose.dev.yml: the services a laptop borrows, never the
  application itself."
  ```
# {{name}} dev infrastructure — for `void dev` on a laptop.
#
# Only the services live in containers; the application runs on your
# machine (`void dev`), which is what keeps the watcher, the repl and
# late binding on your side of the boundary. The production shape —
# the application *as* an image, replicas, a proxy — is a different
# file on purpose: see examples/hub/docker-compose.yml and
# examples/shop/docker-compose.yml in the void repository.
#
#     docker compose -f docker-compose.dev.yml up -d    # or: void services up
#     docker compose -f docker-compose.dev.yml down     # or: void services down
#
# Every host port below is deliberately non-standard, so a postgres or
# redis already running on this machine keeps its own. Nothing here is
# required until a plugin needs it: the generated app keeps its
# guestbook in memory.

name: {{name}}-dev

services:
  # for :void/db-postgres — point the app at it with
  #   VOID_DB_POSTGRES__URL=postgres://{{name}}:{{name}}@localhost:54321/{{name}}
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: {{name}}
      POSTGRES_PASSWORD: {{name}}
      POSTGRES_DB: {{name}}
    ports:
      - "54321:5432"   # host 54321, so a system postgres keeps 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {{name}} -d {{name}}"]
      interval: 5s
      timeout: 5s
      retries: 10

  # for :void/redis (sessions, shared cache, jobs) — point the app at
  # it with
  #   VOID_REDIS__PORT=63790
  redis:
    image: redis:7-alpine
    # no persistence: dev data that survives a `down` is dev data that
    # confuses the next `up`
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "63790:6379"   # host 63790, so a system redis keeps 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  # an SMTP relay with a web inbox: every letter the app sends lands in
  # http://localhost:18025 instead of a real mailbox. For :void/mail —
  #   VOID_MAIL__SMTP__HOST=localhost VOID_MAIL__SMTP__PORT=11025
  mailpit:
    image: axllent/mailpit:latest
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: "1"
      MP_SMTP_AUTH_ALLOW_INSECURE: "1"
    ports:
      - "11025:1025"   # SMTP
      - "18025:8025"   # the inbox

volumes:
  pgdata:
```)

(def smoke-test-template
  "test/smoke-test.janet: the guestbook loop, green from the first run."
  ```
### {{name}} smoke suite — generated by `void new`, green before the
### first line is edited.
###
### test/inject runs each request through the whole chain —
### the router, the middleware, the rendering, the wire serialization —
### without opening a socket: what passes here is what a browser gets.
### Grow it alongside app.janet; `void make resource` writes a suite
### per resource into this same directory.
(import void/core/log :as log)
(import void/test :as test)
# importing a plugin's module is what registers its manifest, which is
# what makes the keyword entries in :plugins below resolvable
(import void/http)
(import void/html)
(import void/htmx)
(import ../app)

# the suite's output is its assertions, not the access log
(log/set-sinks! [(fn [_])])

(test/with-http [c {:plugins [:void/http :void/html :void/htmx :{{name}}/app]}]
  # the page answers
  (def page (test/inject c {:uri "/"}))
  (assert (= 200 (page :status)) "GET / renders")
  (assert (string/find "<form" (test/text page))
          "the schema-driven form is on the page")

  # an invalid submission is refused by the schema, not by a handler
  (def bad (test/inject c {:method :post :uri "/entries"
                           :form {:name "" :message ""}}))
  (assert (string/find "field-errors" (test/text bad))
          "an empty entry re-renders the form with per-field errors")

  # a valid one goes through the whole guestbook loop
  (def good (test/inject c {:method :post :uri "/entries"
                            :form {:name "ada" :message "hello"}}))
  (assert (= 200 (good :status)) "a valid entry is accepted")
  (assert (string/find "ada" (test/text good)) "and listed"))

(print "smoke-test ok")
```)

(def gitignore-template
  "What never belongs in the repository."
  ```
.void/
jpm_tree/
build/
```)

(def readme-template
  "README.md: the four things to run, in the order they are run."
  ```
# {{name}}

A [void](https://github.com/bondiano/void) application — a
server-rendered HTMX guestbook with schema-validated forms.

    jpm --local deps    # pin void in ./jpm_tree (once, and after a bump)
    void dev            # run the app (dev profile: watcher + netrepl)
    void routes         # print the route table
    void repl           # repl into the running process

Run the suite — test/smoke-test.janet drives the guestbook through
the whole request chain (test/inject) with no socket, and
it is green before the first line is edited:

    jpm --local test

Bring up the dev infrastructure — postgres, redis and mailpit on
non-standard ports, no application image (the app runs on your
machine; the production compose shape lives in examples/hub of the
void repository). Nothing needs it until a plugin does:

    docker compose -f docker-compose.dev.yml up -d   # or: void services up
    void services status
    void services down

And when a machine misbehaves, ask it what is missing — toolchain,
libraries, ports:

    void doctor

Scaffold a CRUD resource — entity, form, views, routes, migration and
a suite, every one of them a projection of one declaration:

    void make resource Product name:string price:int notes:text?

Scaffold the pages every application writes by hand — register, sign
in, sign out, a password reset and an address to verify — on top of
void/auth, with a suite that drives all of them:

    void make auth

Lock the composition, so that "why is the middleware stack different in
production" is a diff rather than an investigation:

    void plugins lock   # writes void.lock — commit it
    void plugins check  # in CI

Ship it as one file, with no janet and no source tree on the target
(docs/DEPLOY.md in the void repository):

    jpm --local build
    VOID_PROFILE=prod VOID_HTTP__PORT=8080 ./build/{{name}}

Edit app.janet while `void dev` runs: handler changes are live (late
binding), and new routes or metadata edits rebuild the route table
automatically.
```)

(defn- one [tmpl]
  (fn [name] (template/render tmpl {:name name :void-tag core/release-tag})))

(def- render-project (one project-template))
(def- render-main (one main-template))
(def- render-app (one app-template))
(def- render-config (one config-template))
(def- render-prod-config (one prod-config-template))
(def- render-readme (one readme-template))
(def- render-gitignore (one gitignore-template))
(def- render-smoke-test (one smoke-test-template))

(def render-compose
  "docker-compose.dev.yml for a project name — public, because `void
  services print` renders the same file for a project that predates it
  (printing beats editing: the command writes nothing)."
  (one compose-template))

(def template
  "The project skeleton as data: {:path :render} entries."
  [{:path "project.janet" :render render-project}
   {:path "main.janet" :render render-main}
   {:path "app.janet" :render render-app}
   {:path "config/dev.janet" :render render-config}
   {:path "config/prod.janet" :render render-prod-config}
   {:path "docker-compose.dev.yml" :render render-compose}
   {:path "test/smoke-test.janet" :render render-smoke-test}
   {:path ".gitignore" :render render-gitignore}
   {:path "README.md" :render render-readme}])

(defn- valid-name? [name]
  (peg/match '(* (range "az") (any (+ (range "az") (range "09") "-")) -1)
             name))

(defn- ensure-dirs [path]
  (def parts (string/split "/" path))
  (var cur "")
  (each part (drop -1 parts)
    (set cur (if (empty? cur) part (string cur "/" part)))
    (unless (os/stat cur)
      (os/mkdir cur))))

(defn create
  ``Create a project skeleton: `void new NAME` writes the template into
  ./NAME (which must not exist yet). Returns the tuple of files
  written.``
  [&opt name]
  (when (nil? name)
    (error "usage: void new NAME"))
  (unless (valid-name? name)
    (errorf "project name %q must match [a-z][a-z0-9-]* (it becomes the plugin name %s/app)"
            name name))
  (when (os/stat name)
    (errorf "%q already exists" name))
  (os/mkdir name)
  (def written
    (seq [{:path path :render render} :in template]
      (def full (string name "/" path))
      (ensure-dirs full)
      (spit full (render name))
      full))
  (each f written (print "  created " f))
  (printf "\n  cd %s && void dev" name)
  (tuple ;written))
