### void/cli/make/auth — `void make auth [NAME] [field:type ...]`.
###
### The same idea as `make resource` one layer up. The machinery has
### been there since wave 3 — `auth/password`, the identity, the
### strategies, `challenge!` and the sessions — and every application
### still wrote the same five pages by hand. The generator writes them
### from one declaration too: the entity is the users table
### `void/auth-db` reads, the registration form is `schema/select` over
### it, the migration creates exactly those columns next to the two
### tables `void/auth-db` owns, and reset and verification are the same
### `challenge!` with one claim to tell them apart.
###
### The whole price of writing no file that already exists is
### `report`: everything the scaffold *made necessary* elsewhere has to
### be printed, in full, in one place. A generator that stays out of
### your files and then does not say what it needs has not been
### careful, it has been quiet — and the failures are exactly the kind
### nobody attributes to a generator (a suite that will not import, a
### page whose script the browser refuses with nothing in the terminal
### to say so).

(import ../template)
(import ./spec :as f)
(import ./scaffold)

# -- auth ----------------------------------------------------------------
#
# Everything below generates the five pages every application writes
# by hand on top of machinery it already has: register, sign in, sign
# out, reset a password and verify an address. The two challenges are
# one flow — `auth/challenge!` mints a single-use code, a
# `:void.auth/deliver` gets it to the person, and one route redeems it
# — so what separates them is a claim on the challenge and nothing
# else. Which is why there is one redeem route: a deliverer builds its
# URL from `[:mail-auth :link-path]`, and that is a single path.

(def auth-reserved
  ``Columns the scaffold declares itself. An extra field that names
  one of them would generate a duplicate key in the entity and a
  duplicate column in the migration, so it is refused by name here
  rather than by the parser three files later.``
  [:id :email :password :password-hash :verified-at :created-at])

(defn auth-spec
  ``The value every auth template is a pure function of:

      {:name "user" :entity "User" :plural "users" :table "users"
       :title "User" :project "demo" :plugin "demo/auth"
       :dir "" :module-path "auth" :link-path "/auth/link"
       :driver :void/db-sqlite :version "..." :fields [...]}

  `:fields` are the *extra* profile columns — the four the scaffold
  always declares are not in it, because they are not the caller's to
  rename.``
  [&opt name fields opts]
  (default name "user")
  (default fields [])
  (default opts {})
  (def base (f/kebab name))
  (unless (peg/match '(* (range "az") (any (+ (range "az") (range "09") "-")) -1) base)
    (errorf "account name %q must be a word (User, account, team-member) — it becomes the table and the subject kind (\"%s:42\")"
            name base))
  (each f fields
    (when (index-of (f :name) auth-reserved)
      (errorf "field %q is one the auth scaffold already declares (%s)"
              (f :name)
              (string/join (map |(string/format "%q" $) auth-reserved) " "))))
  (f/check-spec-opts opts)
  # auth's --dir may be empty (the module lands beside app.janet)
  (when-let [d (get opts :dir)]
    (unless (empty? (string d)) (f/check-subpath "--dir" d)))
  (when-let [lp (get opts :link-path)]
    (unless (string/has-prefix? "/" (string lp))
      (errorf "--link-path %q must be an absolute path of this application, like /auth/link" lp)))
  (def plural-name (or (get opts :plural) (f/plural base)))
  (def project (get opts :project "app"))
  (def dir (get opts :dir ""))
  {:name base
   :entity (f/pascal base)
   :plural plural-name
   :table (or (get opts :table) (f/snake plural-name))
   :title (f/title base)
   :project project
   :plugin (string project "/auth")
   :dir dir
   :module-path (if (empty? dir) "auth" (string dir "/auth"))
   :link-path (get opts :link-path "/auth/link")
   :driver (get opts :driver :void/db-sqlite)
   :migrations-dir (get opts :migrations-dir "db/migrations")
   :test-dir (get opts :test-dir "test")
   :version (or (get opts :version) (f/timestamp))
   :fields (tuple ;fields)})

(defn- block
  "Extra lines, indented under a line the template already opened —
  empty when there are no extra fields, which is the common case."
  [n lines]
  (if (empty? lines)
    ""
    (let [pad (string "\n" (string/repeat " " n))]
      (string pad (string/join lines pad)))))

(def auth-template
  "The accounts module: entity, form projections, views, handlers, routes."
  ```
### {{plugin}} — accounts: register, sign in, sign out, reset, verify.
###
### Generated by `void make auth`. Every page here stands on machinery
### that was already in the composition; what the generator wrote is
### the part that is the same in every application and different in
### none of the interesting ways.
###
### The accounts table below is **the application's**: void/auth-db
### reads it (`[:auth-db :users]` says which columns) and never writes
### to it, so registration and a password change are handlers here
### rather than something a plugin does behind them. The sign-up form
### is `schema/select` over that same entity plus the one field that is
### not a column, so a field added to the entity shows up in the form
### with its validation already attached.
###
### **Reset and verification are one flow.** `auth/challenge!` mints a
### single-use code and hands it to whatever delivers (`:void/mail-auth` is one; a challenge nobody delivered is an error).
### There is **one** route that redeems, because a deliverer builds one
### URL — from `[:mail-auth :link-path]` — and which of the two the
### link was for is a claim that travelled on the challenge.
###
### **CSRF is one word here, on three routes.** `form/form` has been
### splicing the token slot since wave 1 and void/security binds it
### — the forms below carry a token because they are forms.
### The check, though, fires on cookie-borne requests — and the POSTs a
### visitor makes *before* they have a session (login, register, the
### reset request) carry no cookie, which is exactly the login-CSRF
### hole. Those three routes ask for the check by name, with the
### `:void.security/csrf` route flag.
###
### Handlers are registered as symbols, so redefining one in the repl —
### or saving this file with `void dev` running — is live.
(import void/core/plugin :as plugin)
(import void/core/schema :as schema)
(import void/db :as db)
(import void/auth :as auth)
(import void/auth/http :as auth-http)
(import void/http/router :as router)
(import void/http/ring :as ring)
(import void/http/wire :as wire)
(import void/html :as html)
(import void/html/form :as form)

# -- the declaration -----------------------------------------------------

(db/defentity {{entity}}
  {:id [:int {:db/pk true :db/type "integer"}]
   :email [:string {:format :email :db/unique true :db/type "text"}]
   # a PHC string ($scrypt$ln=14,r=8,p=1$…), written by
   # `auth/hash-password` and read by void/auth-db's user store. It is
   # optional because an account that only ever arrives by link never
   # sets one — and void/auth's password strategy answers
   # :no-password for it after spending the time it would have spent
   # on a real check
   :password-hash [:optional [:string {:db/type "text"}]]
   :verified-at [:optional [:string {:db/type "text"}]]
   :created-at [:optional [:string {:db/type "text"}]]{{schema-fields}}}
  :db/table "{{table}}")

# -- what the forms submit: projections of the entity, not copies --------

(def Registration
  ``The sign-up form. `schema/merge` composes the projection of the
  entity with the one field that has no place in it — the hash is what
  the table stores, and the plaintext exists for exactly the length of
  one request.``
  (schema/merge (schema/select {{entity}} [:email{{field-keys}}])
                {:password [:string {:min 8 :max 200}]}))

(def Credentials
  "What the sign-in form submits."
  {:email [:string {:format :email}]
   :password [:string {:min 1 :max 200}]})

(def EmailOnly
  "What the \"mail me a reset link\" form submits — an address, and
  deliberately nothing else."
  {:email [:string {:format :email}]})

(def NewPassword
  "What the change-password form submits."
  {:password [:string {:min 8 :max 200}]})

# -- the account behind the identity -------------------------------------
#
# An identity is `{:subject "{{name}}:42" ...}` and nothing more
#: void does not know what a user is, and these three
# functions are where this application says what one is.

(defn- now
  "An ISO-8601 UTC timestamp — text on every engine, which is what
  keeps the migration one file."
  []
  (def d (os/date (os/time) true))
  (string/format "%04d-%02d-%02dT%02d:%02d:%02dZ"
                 (d :year) (inc (d :month)) (inc (d :month-day))
                 (d :hours) (d :minutes) (d :seconds)))

(defn subject-string
  "The subject a record signs in as — `[:auth-db :users :subject-kind]`
  is the `{{name}}` half of it."
  [record]
  (string "{{name}}:" (record :id)))

(defn- find-by-email [email]
  (when email (db/one {{entity}} {:where [:= :email email]})))

(defn- record-of
  "The row an identity points at, or nil."
  [id]
  (when id
    (when-let [n (scan-number (last (auth/subject-of (id :subject))))]
      (db/find {{entity}} n))))

(defn current-record
  "The signed-in account as a row, or nil."
  []
  (record-of (auth/current-user)))

(defn send-verification!
  ``Ask somebody to confirm the address they registered with. The
  claim is what tells this challenge from a password reset when the
  link comes back — `challenge!` refuses if nobody delivered it, which
  is the failure you want: a page that spins forever with nothing in
  any log is the other one.``
  [record]
  (auth/challenge! (subject-string record)
                   {:to (record :email)
                    :claims {:purpose "verify"}}))

(defn- mark-verified! [id]
  (when-let [record (record-of id)]
    (unless (record :verified-at)
      (db/update! {{entity}} (record :id) {:verified-at (now)}))))

# -- views ---------------------------------------------------------------
#
# Plain functions returning hiccup. `layout` is this module's own so
# that these pages render the moment they are generated; point it at
# the application's layout and delete this one.

(defn who-bar
  "Who is signed in, and the way out."
  []
  (if (auth/current-user)
    [:p {:class "who"}
     # the claim comes off the identity, which void/auth-http re-read
     # from the store on this request — no second query for a greeting
     "Signed in as " [:strong (or (auth/claim :email) (auth/subject))] " · "
     [:a {:href "/verify"} "Your address"] " "
     (form/form {} {:action "/logout" :submit "Sign out"})]
    [:p {:class "who"}
     [:a {:href "/login"} "Sign in"] " · "
     [:a {:href "/register"} "Create an account"]]))

(defn layout [content context]
  (html/html5 {:lang "en"}
    [:head
     [:meta {:charset "utf-8"}]
     [:meta {:name "viewport" :content "width=device-width, initial-scale=1"}]
     [:title "{{project}}"]]
    [:body
     [:header (who-bar)]
     [:main content]]))

(defn- page [content]
  (html/page content {:layout layout}))

(defn- message-line [state]
  (when-let [m (get state :message)] [:p {:class "message"} m]))

(defn register-view
  ``The sign-up page. `state` is whatever the handler wants
  re-rendered: :values and :errors put an invalid submission back in
  the form annotated, :message is the one line it is allowed to say.``
  [&opt state]
  (default state {})
  [:div {:id "register"}
   [:h1 "Create an account"]
   (message-line state)
   (form/form Registration
     {:action "/register"
      :values (get state :values)
      :errors (get state :errors)
      :fields {:password {:type "password"}{{form-fields}}}
      :submit "Create an account"})
   [:p [:a {:href "/login"} "Already have an account?"]]])

(defn login-view
  "The sign-in page. :next is where the visitor was going before
  void/auth-http sent them here."
  [&opt state]
  (default state {})
  (def target (get state :next))
  [:div {:id "login"}
   [:h1 "Sign in"]
   (message-line state)
   (form/form Credentials
     {:action (if target (string "/login?next=" (wire/url-encode target)) "/login")
      :values (get state :values)
      :errors (get state :errors)
      :fields {:password {:type "password"}}
      :submit "Sign in"})
   [:p [:a {:href "/password/reset"} "Forgot your password?"] " · "
    [:a {:href "/register"} "Create an account"]]])

(defn reset-view
  "Ask for the address a reset link goes to."
  [&opt state]
  (default state {})
  [:div {:id "reset"}
   [:h1 "Reset your password"]
   (message-line state)
   (form/form EmailOnly
     {:action "/password/reset"
      :values (get state :values)
      :errors (get state :errors)
      :submit "Mail me a link"})])

(defn password-view
  "Set a new password — reached by following a reset link, or from an
  account page."
  [&opt state]
  (default state {})
  [:div {:id "password"}
   [:h1 "Choose a new password"]
   (message-line state)
   (form/form NewPassword
     {:action "/password"
      :values (get state :values)
      :errors (get state :errors)
      :fields {:password {:type "password"}}
      :submit "Save"})])

(defn verify-view
  "Where the confirmation link is asked for again — a link expires, and
  a flow with no way to send a second one is a dead end with a support
  ticket attached."
  [record]
  [:div {:id "verify"}
   [:h1 "Your address"]
   (if (get record :verified-at)
     [:p {:class "message"}
      (string (get record :email "") " is confirmed.")]
     [:div
      [:p "We sent a confirmation link to "
       [:strong (get record :email "")] "."]
      (form/form {} {:action "/verify" :submit "Send it again"})])])

(defn notice-view
  "One line, and nothing to fill in."
  [message]
  [:div {:id "notice"} [:p {:class "message"} message]])

# -- handlers ------------------------------------------------------------

(defn register-form
  "GET /register"
  [req]
  (page (register-view)))

(defn register
  ``POST /register — an account with a password.

  The sign-in that follows goes through the ordinary password path
  rather than trusting the row that was just written: one code path
  signs anybody in, so there is one place where that can be wrong.``
  [req]
  (form/submit Registration (req :form)
    {:ok (fn [v]
           (if (find-by-email (v :email))
             (page (register-view {:values (req :form)
                                   :message "That address already has an account — sign in instead."}))
             (do
               (def created
                 (db/insert! {{entity}}
                             {:email (v :email){{inserts}}
                              :password-hash (auth/hash-password (v :password))
                              :created-at (now)}))
               (def check (auth/check-password (auth/user-store)
                                               {:email (v :email) :password (v :password)}))
               (auth-http/login! req (check :identity))
               (send-verification! created)
               (ring/redirect "/"))))
     :invalid (fn [values errors]
                (page (register-view {:values values :errors errors})))}))

(defn login-form
  "GET /login — where [:auth-http :login-path] points."
  [req]
  (page (login-view {:next (get (or (req :query) {}) "next")})))

(defn login
  ``POST /login — the password path, and nothing else.

  Whatever went wrong, the page says the same thing:
  `check-password` distinguishes an unknown address from a wrong
  password and spends the same time on both (it hashes even when
  there is no account), and telling the visitor which it was would
  hand that distinction straight back.``
  [req]
  (defn refused [values]
    (page (login-view {:values values
                       :next (get (or (req :query) {}) "next")
                       :message "Those credentials do not match an account."})))
  (form/submit Credentials (req :form)
    {:ok (fn [v]
           (if-let [id (get (auth/check-password (auth/user-store) v) :identity)]
             (do
               (auth-http/login! req id)
               # where the visitor was going, as a path of this
               # application and nothing else: a `next` that is somebody
               # else's origin is an open redirect with a sign-in page
               # attached
               (ring/redirect (auth-http/safe-next req)))
             (refused (req :form))))
     :invalid (fn [values _] (refused values))}))

(defn logout
  "POST /logout — drop the identity and rotate the session id."
  [req]
  (auth-http/logout! req)
  (ring/redirect "/"))

(defn reset-form
  "GET /password/reset"
  [req]
  (page (reset-view)))

(defn request-reset
  ``POST /password/reset — mail a link that signs them in long enough
  to choose a new password.

  **The answer is the same whether or not the address has an
  account.** A page that said "no such account" would be a way to ask
  this application who its {{plural}} are, one address at a time — the
  same reasoning that makes `check-password` spend its time on an
  unknown login.``
  [req]
  (form/submit EmailOnly (req :form)
    {:ok (fn [v]
           (when-let [record (find-by-email (v :email))]
             (auth/challenge! (subject-string record)
                              {:to (record :email)
                               :claims {:purpose "reset"}}))
           (page (reset-view
                   {:values (req :form)
                    :message "If that address has an account, a link is on its way."})))
     :invalid (fn [values _]
                (page (reset-view
                        {:values values
                         :message "That does not look like an email address."})))}))

(defn link
  ``GET {{link-path}}?h=&c= — the one path a letter points at
  ([:mail-auth :link-path]), for both challenges.

  `redeem!` takes the challenge out of the store *before* it checks
  the code, so a link works once and a wrong one is
  spent: the visitor asks for another, which costs them a click and an
  attacker a full guess per try. What the link was for is a claim that
  travelled on the challenge — no second table, and no second route.``
  [req]
  (def query (or (req :query) {}))
  (if-let [id (auth/redeem! (get query "h") (get query "c"))]
    (do
      (auth-http/login! req id)
      (if (= "reset" (get-in id [:claims :purpose]))
        (ring/redirect "/password/edit")
        (do
          (mark-verified! id)
          (ring/redirect "/"))))
    (page (login-view
            {:message "That link has expired or has already been used."}))))

(defn password-form
  "GET /password/edit"
  [req]
  (page (password-view)))

(defn update-password
  "POST /password — the route is :required, so there is somebody to
  change the password of."
  [req]
  (def record (current-record))
  (form/submit NewPassword (req :form)
    {:ok (fn [v]
           (if record
             (do
               (db/update! {{entity}} (record :id)
                           {:password-hash (auth/hash-password (v :password))})
               (page (notice-view "Your password has been changed.")))
             (page (password-view {:values (req :form)}))))
     :invalid (fn [values errors]
                (page (password-view {:values values :errors errors})))}))

(defn verify-form
  "GET /verify"
  [req]
  (page (verify-view (current-record))))

(defn resend-verification
  "POST /verify — another confirmation link for the signed-in account.
  A confirmed address does not get one: the link signs whoever holds
  it in, and there is no reason to keep minting those."
  [req]
  (when-let [record (current-record)]
    (unless (record :verified-at)
      (send-verification! record)))
  (page (notice-view "A confirmation link is on its way.")))

# -- routes --------------------------------------------------------------
#
# Every route says what access it needs rather than leaning on
# [:auth-http :default]: the default is :public, an application that
# flips it to :required has taken a deny-by-default posture on purpose,
# and these twelve routes have to keep meaning the same thing under
# both. The names are also what a policy asks about — one
# name, read by more than one thing.

(router/defroutes :{{project}}/auth-routes
  (GET "/register" register-form {:name :auth/register-form
                                  :void.auth/access :public})
  # the three anonymous POSTs carry no session cookie, so the
  # cookie-borne CSRF rule never sees them — login CSRF (being signed
  # into an attacker's account) needs the check asked for by name
  (POST "/register" register {:name :auth/register
                              :void.auth/access :public
                              :void.security/csrf true})
  (GET "/login" login-form {:name :auth/login-form
                            :void.auth/access :public})
  (POST "/login" login {:name :auth/login
                        :void.auth/access :public
                        :void.security/csrf true})
  (POST "/logout" logout {:name :auth/logout
                          :void.auth/access :public})
  (GET "/password/reset" reset-form {:name :auth/reset-form
                                     :void.auth/access :public})
  (POST "/password/reset" request-reset {:name :auth/reset-request
                                         :void.auth/access :public
                                         :void.security/csrf true})
  # a GET that signs somebody in is safe here for the reason a password
  # POST is: the credential is in the URL and it is single-use
  (GET "{{link-path}}" link {:name :auth/link :void.auth/access :public})
  (GET "/password/edit" password-form {:name :auth/password-form
                                       :void.auth/access :required})
  (POST "/password" update-password {:name :auth/password-update
                                     :void.auth/access :required})
  (GET "/verify" verify-form {:name :auth/verify-form
                              :void.auth/access :required})
  (POST "/verify" resend-verification {:name :auth/verify-resend
                                       :void.auth/access :required}))

(plugin/defplugin {{plugin}}
  :doc "{{title}} accounts: register, sign in, sign out, password reset and address verification, over void/auth."
  :version "0.1.0"
  :requires {:void/http ">=0.0.1" :void/html ">=0.0.1" :void/db ">=0.0.1"
             :void/auth ">=0.0.1" :void/auth-http ">=0.0.1"
             :void/auth-db ">=0.0.1"})
```)

(def auth-migration-template
  "The users table, and the two tables void/auth-db owns beside it."
  ```
### {{table}} — generated by `void make auth {{name}}`.
###
### Two owners, one file. `{{table}}` is the application's:
### void/auth-db *reads* it (`[:auth-db :users]` says which columns)
### and never writes to it, which is why registration and a password
### change are handlers in {{module-path}}.janet. The other two tables
### are void's own — API-token digests and single-use one-time codes —
### and void/auth-db ships their DDL as data rather than as a migration
### of its own, because a migration timeline belongs to the application
###.
###
### What a step returns is executed: void/db/builder compiles the
### statements for whichever engine is running, which is what keeps one
### migration file portable. Apply it with `void db migrate`.
(import void/auth/db :as auth-db)

(defn up []
  [{:create-table "{{table}}"
    :columns [[:id :serial {:primary-key true}]
              [:email :text {:null false :unique true}]
              # a PHC string: the algorithm and its cost travel inside
              # the value, so raising the cost later is a config change
              # rather than a migration nobody can write.
              # Nullable — an account that only arrives by link has none
              [:password-hash :text]
              # text on both engines, so a row reads the same on either
              [:verified-at :text]
              [:created-at :text]{{columns}}]}
   ;(auth-db/tables)])

(defn down []
  [;(auth-db/drop-tables)
   {:drop-table "{{table}}"}])
```)

(def auth-test-template
  "The suite: every flow the scaffold ships, through the real stack."
  ```
### The accounts scaffold — generated by `void make auth`.
###
### Every flow driven the way a browser drives it: test/inject
### runs a request through the whole chain — the session,
### the CSRF check, the strategy chain, the route table — without
### opening a socket, so what passes here is what a browser gets.
###
### **The composition is written out** rather than read from
### main.janet, so that this suite runs the moment it is generated —
### before those plugins have been added there. Once they have, replace
### the list with main.janet's and the suite follows the application.
###
### **Delivery is a plugin of this file's own.** `auth/challenge!`
### refuses a challenge nobody delivered; in production
### :void/mail-auth is what delivers, and here it is five lines that
### keep the code where an assertion can read it — which is how the
### reset and the verification are proven without a mailbox.
(import void/core/plugin :as plugin)
(import void/core/log :as log)
(import void/test :as test)
(import void/db :as db)
# importing a plugin's module is what registers its manifest, which is
# what makes a keyword entry in :plugins below resolvable. The module
# under test imports void/auth and void/auth-http itself; these four it
# does not name, and they are in the composition all the same
(import void/crypto)
(import void/auth/db)
(import void/security)
(import {{driver-module}})
(import ../{{module-path}} :as accounts)

# -- the deliverer -------------------------------------------------------

(def delivered
  "Every challenge this suite caused, newest last."
  @[])

(def capture
  (plugin/manifest 'test/capture-challenges
    :doc "Keeps magic links where an assertion can read them."
    :contributes {:void.auth/deliver
                  [{:name :test/capture
                    :fn (fn capture [payload]
                          (array/push delivered payload)
                          true)}]}))

# -- the composition -----------------------------------------------------

(def sqlite-path
  (string (or (os/getenv "TMPDIR") "/tmp")
          "/{{project}}-auth-test-" (os/time) ".sqlite3"))

(def plugins
  [:void/http :void/html
   :void/db {{driver}}
   # every hash and every code comes from void/crypto: this
   # composition hashes nothing itself
   :void/crypto :void/auth :void/auth-http :void/auth-db
   # the CSRF token the forms below carry without asking
   :void/security
   capture
   :{{plugin}}])

(def config
  {:env @{}
   :cli {:db {:migrations {:dir "{{migrations-dir}}"}}
         :db-sqlite {:path sqlite-path}
         :http {:session {:enabled true}}
         # three interfaces have two implementations each — the memory
         # stores void/auth ships and the database ones void/auth-db
         # does — and the kernel refuses to guess
         :void/auth-user-store {:impl :auth.db/users}
         :void/auth-token-store {:impl :auth.db/tokens}
         :void/auth-challenge-store {:impl :auth.db/challenges}
         :auth-db {:users {:table "{{table}}"
                           :subject-kind "{{name}}"
                           :email-column "email"
                           :password-column "password_hash"
                           # on the identity, so a page can greet
                           # somebody without a second query
                           :claims-columns ["email"]}}
         :auth-http {:unauthenticated :redirect :login-path "/login"}
         # what the configured hasher costs is pinned in void/crypto;
         # this suite signs in a dozen times and does not need it
         :auth {:scrypt {:ln 10}}
         :crypto {:kdf {:in-thread false}}}})

# -- helpers -------------------------------------------------------------

(defn- text [resp] (test/text resp))

(defn- token-of
  "The CSRF token out of a rendered form — no page below asked for one."
  [resp]
  (first (peg/match ~(* (thru `name="_csrf"`) (thru `value="`) (<- (to `"`))) (text resp))))

(defn- message-of
  "The one line a page is allowed to say."
  [resp]
  (first (peg/match ~(* (thru `class="message">`) (<- (to "<"))) (text resp))))

(defn- token-for [client uri]
  (or (token-of (test/inject client {:uri uri}))
      (errorf "no CSRF token on %s" uri)))

(defn- link-of [challenge]
  (string "{{link-path}}?h=" (challenge :handle) "&c=" (challenge :code)))

(log/set-sinks! [(fn [_])])

(test/with-http [c {:plugins plugins
                    :profile :test
                    :config config
                    :only [:http/kernel :crypto/lib :auth/registry]}]
  (db/migrate-up! {:dir "{{migrations-dir}}"})

  # -- registration ------------------------------------------------------

  (def form-page (test/inject c {:uri "/register"}))
  (assert (= 200 (form-page :status)) "the sign-up page renders")
  (assert (token-of form-page)
          "and carries a CSRF token nobody wrote a line for: form/form splices the slot, void/security binds it")

  (def registered
    (test/inject c {:uri "/register"
                    :headers {"x-csrf-token" (token-of form-page)}
                    :form {:email "ada@example.com"
                           :password "correct horse battery"{{sample}}}}))
  (assert (= 302 (registered :status)) "registering signs the visitor in")

  (def ada (db/one accounts/{{entity}} {:where [:= :email "ada@example.com"]}))
  (assert ada "the account is a row in {{table}}")
  (assert (not (string/find "correct horse" (ada :password-hash)))
          "and the column holds a hash, not the password")
  (assert (string/has-prefix? "$" (ada :password-hash))
          "a PHC string: the algorithm and its cost travel inside the value")

  # an anonymous POST carries no session cookie, which is exactly the
  # request the cookie-borne rule cannot see — the route asks for the
  # check by name (:void.security/csrf true), so login CSRF is closed
  (assert (= 403 ((test/inject (test/client (c :boot))
                               {:uri "/register"
                                :form {:email "eve@example.com"
                                       :password "any password"{{sample}}}})
                  :status))
          "an anonymous POST without the token is refused — signing a visitor into an account they did not ask for is CSRF too")

  (def second-visitor (test/client (c :boot)))
  (def taken
    (test/inject second-visitor
                 {:uri "/register"
                  :headers {"x-csrf-token" (token-for second-visitor "/register")}
                  :form {:email "ada@example.com"
                         :password "another password"{{sample}}}}))
  (assert (string/find "already has an account" (text taken))
          "a second account for the same address is refused, and says so")
  (assert (= 1 (db/count accounts/{{entity}})))

  # -- verifying the address ---------------------------------------------

  (assert (= 1 (length delivered))
          "registering asks the visitor to confirm their address — and challenge! would have raised if nobody delivered it")
  (assert (= "verify" (get-in (last delivered) [:claims :purpose]))
          "the claim is what tells this challenge from a reset")
  (assert (= "ada@example.com" ((last delivered) :to)))
  (assert (not (ada :verified-at)) "not verified until the link is followed")

  # a link expires in fifteen minutes; a flow with no second one is a
  # dead end with a support ticket attached
  (assert (string/find "We sent a confirmation link"
                       (text (test/inject c {:uri "/verify"}))))
  (assert (= 200 ((test/inject c {:method :post :uri "/verify"
                                  :headers {"x-csrf-token" (token-for c "/password/edit")}})
                  :status)))
  (assert (= 2 (length delivered)) "and asking again sends another")

  (def verification (last delivered))
  (assert (= 302 ((test/inject c {:uri (link-of verification)}) :status)))
  (assert ((db/find accounts/{{entity}} (ada :id)) :verified-at)
          "following the link is what marks the address verified")

  (def replayed (test/inject (test/client (c :boot))
                             {:uri (link-of verification)}))
  (assert (string/find "expired or has already been used" (text replayed))
          "a link works once: redeem takes the challenge out of the store before it checks the code")

  (assert (string/find "is confirmed" (text (test/inject c {:uri "/verify"}))))
  (array/clear delivered)
  (assert (= 200 ((test/inject c {:method :post :uri "/verify"
                                  :headers {"x-csrf-token" (token-for c "/password/edit")}})
                  :status)))
  (assert (empty? delivered)
          "and a confirmed address stops minting links that sign whoever holds them in")

  # -- signing out, and back in ------------------------------------------

  (assert (= 302 ((test/inject c {:method :post :uri "/logout"
                                  :headers {"x-csrf-token" (token-for c "/login")}})
                  :status)))

  (def anon-token (token-for c "/login"))
  (defn- sign-in [email password]
    (test/inject c {:uri "/login"
                    :headers {"x-csrf-token" anon-token}
                    :form {:email email :password password}}))

  (def wrong (sign-in "ada@example.com" "not it"))
  (def unknown (sign-in "nobody@example.com" "not it"))
  (assert (= (wrong :status) (unknown :status)))
  (assert (= (message-of wrong) (message-of unknown))
          "a wrong password and an unknown address say exactly the same thing — telling them apart is a user-enumeration API, and check-password spends the same time on both")
  (each said ["no such" "unknown" "wrong password" "not registered"]
    (assert (not (string/find said (string/ascii-lower (text unknown))))
            (string "and the page does not say " said)))

  (assert (= 302 ((sign-in "ada@example.com" "correct horse battery") :status))
          "the right password signs in")

  # -- CSRF ---------------------------------------------------------------
  #
  # The credential rides on a cookie, which is exactly when CSRF
  # applies.

  (assert (= 403 ((test/inject c {:uri "/password"
                                  :form {:password "a password from nowhere"}})
                  :status))
          "a signed-in POST without the token is refused before the handler runs")

  # -- what :void.auth/access :required means ------------------------------

  (def anon (test/client (c :boot)))
  (def redirected (test/inject anon {:uri "/password/edit"}))
  (assert (= 302 (redirected :status))
          "an unauthenticated request to a protected route goes to the sign-in page, because this composition said :redirect")
  (assert (string/has-prefix? "/login?next=" (get-in redirected [:headers "location"]))
          "carrying where it was going")

  # -- the reset ----------------------------------------------------------

  (array/clear delivered)
  (def visitor (test/client (c :boot)))
  (def asked
    (test/inject visitor {:uri "/password/reset"
                          :headers {"x-csrf-token" (token-for visitor "/password/reset")}
                          :form {:email "ada@example.com"}}))
  (assert (string/find "on its way" (text asked)))
  (assert (= 1 (length delivered)))
  (def reset (last delivered))
  (assert (= "reset" (get-in reset [:claims :purpose])))

  (def landed (test/inject visitor {:uri (link-of reset)}))
  (assert (= "/password/edit" (get-in landed [:headers "location"]))
          "the link signs them in and lands on the form for a new password")

  (def edit (test/inject visitor {:uri "/password/edit"}))
  (assert (= 200 (edit :status)))
  (assert (= 200 ((test/inject visitor {:uri "/password"
                                        :headers {"x-csrf-token" (token-of edit)}
                                        :form {:password "a longer new password"}})
                  :status)))

  (def after (test/client (c :boot)))
  (defn- try-login [password]
    (test/inject after {:uri "/login"
                        :headers {"x-csrf-token" (token-for after "/login")}
                        :form {:email "ada@example.com" :password password}}))
  (assert (= 200 ((try-login "correct horse battery") :status))
          "the old password no longer signs anybody in")
  (assert (= 302 ((try-login "a longer new password") :status))
          "and the new one does")

  (array/clear delivered)
  (def stranger
    (test/inject visitor {:uri "/password/reset"
                          :headers {"x-csrf-token" (token-for visitor "/password/reset")}
                          :form {:email "nobody@example.com"}}))
  (assert (= (message-of asked) (message-of stranger))
          "an address with no account gets the same page — anything else is a way to ask this application who its {{plural}} are")
  (assert (empty? delivered) "and nothing was sent to it"))

(log/set-sinks! nil)
(os/rm sqlite-path)

(print "auth-test ok")
```)

(defn- auth-migration-path [spec]
  (string (spec :migrations-dir) "/" (spec :version)
          "_create_" (spec :table) ".janet"))

(defn- auth-substitutions
  "Every hole the built-in auth templates have, filled from the spec.
  An override that wants one of them gets it by calling this."
  [spec]
  (def fields (spec :fields))
  (def ff (filter identity (map f/form-field-source fields)))
  {:name (spec :name)
   :entity (spec :entity)
   :plural (spec :plural)
   :table (spec :table)
   :title (spec :title)
   :project (spec :project)
   :plugin (spec :plugin)
   :dir (spec :dir)
   :module-path (spec :module-path)
   :link-path (spec :link-path)
   # the plugin keyword as it is written in a :plugins list, and the
   # module the suite imports to register that manifest
   :driver (string/format "%q" (spec :driver))
   :driver-module (string (spec :driver))
   :migrations-dir (spec :migrations-dir)
   :version (spec :version)
   :field-keys (string/join (map |(string/format " %q" ($ :name)) fields) "")
   :schema-fields
   (block 3 (map |(string/format "%q %s" ($ :name) (f/node-source $)) fields))
   :columns (block 14 (map f/column-source fields))
   :inserts
   (block 21 (map |(string/format "%q (v %q)" ($ :name) ($ :name)) fields))
   :form-fields (block 15 ff)
   :sample
   (string/join (map (fn [f] (string/format " %q %s"
                                            (f :name)
                                            (get (f/field-type (f :type)) :sample)))
                     fields)
                "")})

(def auth-template-entries
  ``The built-in auth template, as data: one entry per file, each with
  the `:key` a project override is named after, a `:path` and a pure
  `:render`.``
  [{:key :auth
    :path (fn [s] (string (s :module-path) ".janet"))
    :render (fn [s] (template/render auth-template (auth-substitutions s)))}
   {:key :migration
    :path auth-migration-path
    :render (fn [s] (template/render auth-migration-template
                                     (auth-substitutions s)))}
   {:key :test
    :path (fn [s] (string (s :test-dir) "/auth-test.janet"))
    :render (fn [s] (template/render auth-test-template
                                     (auth-substitutions s)))}])

(def override-dir
  "Where a project keeps its own auth templates."
  "templates/auth")

# -- what the generator did not do ---------------------------------------
#
# `make` writes new files and edits none (see the module header), and
# the whole cost of that decision falls here: everything the scaffold
# *made necessary* in a file somebody has already edited has to be
# said, in full, in one place, or it becomes folklore — a paste
# remembered from the last project, and an application that boots into
# a page whose script the browser refuses with nothing in the terminal
# to say so. examples/hub found all three of these the expensive way
#, which is why they are printed rather than assumed.

(def driver-dependencies
  ``The jpm dependency a driver's *library* comes from, by driver. Only
  sqlite has one: void/db-postgres and void/db-mysql open libpq and
  libmysqlclient through `ffi/` at run time, so nothing has to be
  installed for the module to load.

  The void bundle deliberately does not carry janet-lang/sqlite3
: void/db-sqlite is a plugin an application composes, so
  the application declares it. The suite this generator writes boots
  that driver — so on a tree that has only void, the generated suite
  fails on its first import, with the driver's own (good) message and
  no hint that a generator caused it.``
  {:void/db-sqlite "https://github.com/janet-lang/sqlite3.git"})

(defn auth-report
  ``The lines `void make auth` prints after it has written its files:
  the three edits it did not make, in the order they have to happen.
  A pure function of the spec, so a test can read what a person is
  told rather than only what was written to disk.``
  [spec]
  (def out @[])
  (defn say [& parts] (array/push out (string ;parts)))
  (def dep (get driver-dependencies (spec :driver)))

  (say "  none of the three edits below was made for you: `void make` writes")
  (say "  new files and never rewrites a file you have edited — a generator")
  (say "  that does is one nobody dares run twice. They are printed instead,")
  (say "  in the order they have to happen.")

  (var step 0)
  (defn heading [& parts]
    (++ step)
    (say)
    (say "  " step ". " ;parts))

  (when dep
    (heading "project.janet — :dependencies")
    (say)
    (say "       " (string/format "%q" dep))
    (say)
    (say "     " (string/format "%q" (spec :driver)) " is a plugin an application composes, so the")
    (say "     application installs its library: the void bundle leaves it out on")
    (say "     purpose. Without this line, on a tree that has only")
    (say "     void, " (spec :test-dir) "/auth-test.janet fails on its first import."))

  (def composition
    [[(string ":" (spec :plugin)) "the routes, the entity and the pages"]
     [(string ":void/db " (string/format "%q" (spec :driver)))
      "the entity layer and a driver, if not there yet"]
     [":void/crypto" "every hash and every code is minted here"]
     [":void/auth :void/auth-http :void/auth-db"
      "the identity, the session and the stores"]
     [":void/security" "the CSRF token the forms already carry"]
     [":void/mail :void/mail-auth" "what gets a link to the person"]])
  (def width (max ;(map |(length (first $)) composition)))
  (heading "main.janet — :plugins")
  (say)
  (each [names doc] composition
    (say "       " names (string/repeat " " (- width (length names))) "  " doc))

  (heading "config/dev.janet (or default.janet)")
  (say)
  (say "       {:http {:session {:enabled true}}")
  (say "        :void/auth-user-store {:impl :auth.db/users}")
  (say "        :void/auth-token-store {:impl :auth.db/tokens}")
  (say "        :void/auth-challenge-store {:impl :auth.db/challenges}")
  (say "        :auth-db {:users {:table " (string/format "%q" (spec :table))
       " :subject-kind " (string/format "%q" (spec :name)))
  (say "                          :email-column \"email\"")
  (say "                          :password-column \"password_hash\"")
  (say "                          :claims-columns [\"email\"]}}")
  (say "        :auth-http {:unauthenticated :redirect :login-path \"/login\"}")
  (say "        :mail-auth {:link-path " (string/format "%q" (spec :link-path)) "}")
  (say "        :mail {:transport :file :base-url \"http://localhost:8080\"")
  (say "               :from \"" (spec :project) " <no-reply@" (spec :project) ".example>\"}")
  (say "        :security {:csp {:policy {:default-src [:self]")
  (say "                                  :script-src [:self \"https://unpkg.com\"]")
  (say "                                  :base-uri [:self]")
  (say "                                  :form-action [:self]")
  (say "                                  :frame-ancestors [:none]")
  (say "                                  :object-src [:none]")
  (say "                                  :img-src [:self \"data:\"]}}}}")
  (say)
  (say "     The last key is there because this generator put :void/security in")
  (say "     the composition above, and its default policy is `default-src")
  (say "     'self'` — which refuses the htmx `void new` loads from unpkg. The")
  (say "     browser says so in its console and nowhere else, so the line is")
  (say "     printed here rather than found later. `:policy` replaces the")
  (say "     defaults rather than merging into them (half a policy is a")
  (say "     different policy), which is why the whole of it is written out;")
  (say "     serve htmx from your own assets and `:script-src [:self]` is the")
  (say "     only line that changes.")

  (say)
  (say "  a challenge nobody delivered is an error: without")
  (say "  :void/mail-auth — or a :void.auth/deliver of your own — registering")
  (say "  and resetting raise rather than mail nothing.")
  (say)
  (say "  then:")
  (say)
  (when dep (say "    jpm --local deps         # the driver's library"))
  (say "    void db migrate")
  (say "    void dev                 # /register")
  (say)
  (tuple ;out))

(def command
  ``What `void make auth` takes, as the same declaration every other
  void command carries: void/core/cli parses argv against it and
  renders its `--help`.

  `--no-input` is accepted and inert — this generator never asks
  anything, so the same command already runs in CI, and a script
  written for `make resource` should not fall over on the flag.``
  {:name :make/auth
   :doc "Scaffold register/login/logout, reset and verify"
   :args ["[NAME]" "[FIELD:TYPE...]"]
   :flags {"--table" {:key :table :doc "table name (the pluralizer is a guess)"}
           "--plural" {:key :plural :doc "plural of NAME"}
           "--dir" {:key :dir :doc "where the module lands (default: beside app.janet)"}
           "--migrations-dir" {:key :migrations-dir :doc "default: db/migrations"}
           "--test-dir" {:key :test-dir :doc "default: test"}
           "--project" {:key :project :doc "the plugin's namespace (default: this project)"}
           "--link-path" {:key :link-path :doc "what [:mail-auth :link-path] will point at"}
           "--driver" {:key :driver :type :keyword :doc "the driver the generated suite boots on"}
           "--version" {:key :version :doc "the migration's version, for a reproducible run"}
           "--force" {:key :force :type :bool :doc "overwrite what is there"}
           "--dry-run" {:key :dry-run :type :bool :doc "print instead of writing"}
           "--no-input" {:key :no-input :type :bool :doc "accepted and inert — nothing here asks"}}})

(defn create
  ``The body of `void make auth [NAME] [field:type ...]`.

  NAME is what an account is called here — `user` by default. It
  becomes the entity, the table and the subject kind, so an identity
  reads `"user:42"` and `void/authz` can tell a person from a service
  token by looking at it. Extra `field:type` arguments are profile
  columns: they join the entity, the migration and the sign-up form,
  and everything else the scaffold declares is not the caller's to
  rename.

  Returns the tuple of paths written — or, under `--dry-run`, the
  paths it would have written.``
  [opts &opt name & field-args]
  (def fields (map f/parse-field field-args))
  (def spec-opts
    (merge {:project (f/project-name)}
           (table/to-struct opts)
           # `--driver :void/db-sqlite` and `--driver void/db-sqlite`
           # are the same driver; a leading colon is how a reader
           # writes a keyword and not part of its name
           (if-let [d (opts :driver)]
             {:driver (keyword (string/trim (string d) ":"))}
             {})))
  (def spec (scaffold/specced
              |(auth-spec name fields (merge spec-opts $))
              opts))
  (def written
    (scaffold/run! spec (scaffold/templates auth-template-entries override-dir) opts))
  (unless (opts :dry-run)
    (print)
    (each line (auth-report spec) (print line)))
  written)
