### void/cli/make/job — `void make job NAME [arg:type ...]`.
###
### A job is the smallest thing in void that is still four decisions:
### which queue it runs on, how many attempts it gets before the dead
### letter queue, whether two enqueues of the same arguments are one
### run, and — with `--schedule` — when it fires without anyone
### enqueueing it. Written by hand those are defaults nobody chose;
### written here they are a `defjob` head with each of them on a line.
###
### The body is the one part the generator cannot write. What it can do
### is prove, in the generated suite, that the declaration around it
### holds: the job is registered under the name a schedule and `void
### jobs retry` use, it carries the queue it says it does, and
### `jobs/perform` hands the body the arguments an enqueue passed —
### with no worker, no backend and no queue involved.

(import ../template)
(import ./spec :as f)
(import ./scaffold)

(def job-template
  "The job module: the declaration, the body and the plugin manifest."
  ```
### {{plugin}} — the {{name}} job.
###
### `defjob` is the declaration and the body at once: the head says
### where the work runs and what happens when it fails, and everything
### under it is ordinary Janet the worker calls with the arguments an
### enqueue passed.
###
### Nothing here runs on the request path. `(jobs/enqueue :{{name}} ...)`
### from a handler returns as soon as the record is written — in the
### same transaction as your own writes, when the backend is the
### database — and a worker picks it up.
(import void/core/log :as log)
(import void/core/plugin :as plugin)
(import void/jobs :as jobs)

(def log-ns "{{project}}.jobs.{{name}}")

(jobs/defjob {{name}}
  "What this job is for, in one sentence."
  {:queue {{queue}}
   # tries before the record goes to the dead letter queue, where
   # `void jobs retry --state dead` can find it again
   :max-attempts {{max-attempts}}
   # :args collapses a burst of enqueues carrying the same arguments
   # into one run; drop the line to let every enqueue be its own record
   :unique :args}
  [{{params}}]
  (log/info "{{name}}"{{log-args}} :ns log-ns)
  # the work goes here — and it may block: this runs on a worker fiber,
  # never on the request path
  :done)
{{schedule}}
(plugin/defplugin {{plugin}}
  :doc "The {{title}} job."
  :version "0.1.0"
  :requires {:void/jobs ">=0.0.1"})
```)

(def schedule-template
  "The defschedule `--schedule` adds, or nothing."
  ```

(jobs/defschedule {{name}}-schedule
  "{{cron}}"
  :{{name}})
```)

(def test-template
  "The suite: the declaration, and the body run without a queue."
  ```
### The {{name}} job — generated by `void make job`.
###
### The declaration is what this proves. A job is reached by *name* —
### a schedule names it, an enqueue names it, `void jobs retry` names
### it — so the registration and the policy under that name are the
### contract, and the body is what you assert on once there is one.
(import void/jobs :as jobs)
(import ../{{module-path}} :as job)

(def d (assert (jobs/job-of :{{name}}) "the job is registered under its name"))
(assert (= {{queue}} (get-in d [:opts :queue]))
        "runs on the queue it declares")
(assert (= {{max-attempts}} (get-in d [:opts :max-attempts]))
        "and gets the attempts it declares")

# performed directly: no worker, no backend, no queue — the body, with
# the arguments an enqueue would have carried to it
(assert (= :done (jobs/perform :{{name}}{{sample-args}}))
        "the body runs on the arguments the enqueue passed")

(print "{{name}}-job-test ok")
```)

(defn- substitutions
  {:params [{:name :string :project :string :plugin :string :dir :string
             :module-path :string :test-dir :string :queue :any
             :max-attempts :number :schedule :any
             :fields [{:name :keyword :type :keyword :optional? :boolean
                       :entity :keyword? :rel :keyword? :table :string?}]}]
   :ret {:name :string :title :string :project :string :plugin :string
         :module-path :string :queue :string :max-attempts :string
         :params :string :log-args :string :sample-args :string :schedule :string}}
  "The template holes job-template and schedule-template read, built
  from a job spec."
  [spec]
  (def fields (spec :fields))
  (def names (map |(f/kebab (string ($ :name))) fields))
  {:name (spec :name)
   :title (f/title (spec :name))
   :project (spec :project)
   :plugin (spec :plugin)
   :module-path (spec :module-path)
   :queue (string/format "%q" (spec :queue))
   :max-attempts (string (spec :max-attempts))
   :params (string/join names " ")
   :log-args (string/join (map |(string/format " :%s %s" $ $) names) "")
   :sample-args
   (string/join (map |(string " " (get (f/field-type ($ :type)) :sample)) fields) "")
   :schedule
   (if (spec :schedule)
     (template/render schedule-template {:name (spec :name) :cron (spec :schedule)})
     "")})

(def entries
  "The two files, and the keys a project's own templates are named after."
  [{:key :job
    :path (fn [s] (string (s :module-path) ".janet"))
    :render (fn [s] (template/render job-template (substitutions s)))}
   {:key :test
    :path (fn [s] (string (s :test-dir) "/" (s :name) "-job-test.janet"))
    :render (fn [s] (template/render test-template (substitutions s)))}])

(def override-dir
  "Where a project keeps its own job templates."
  "templates/job")

(defn job-spec
  {:params [:string
            @[{:name :keyword :type :keyword :optional? :boolean
               :entity :keyword? :rel :keyword? :table :string?}]
            (or {:dir :string? :project :string? :test-dir :string?
                 :queue :any :max-attempts :number? :schedule :any & r}
                :nil)]
   :ret {:name :string :project :string :plugin :string :dir :string
         :module-path :string :test-dir :string :queue :any
         :max-attempts :number :schedule :any
         :fields [{:name :keyword :type :keyword :optional? :boolean
                   :entity :keyword? :rel :keyword? :table :string?}]}
   :throws [:string]}
  ``The value both templates are a pure function of. `:fields` are the
  job's *arguments* — a job takes values, not a row or a closure,
  because the record it is enqueued as has to survive a restart.``
  [name fields &opt opts]
  (default opts {})
  (def base (f/kebab name))
  (unless (peg/match '(* (range "az") (any (+ (range "az") (range "09") "-")) -1) base)
    (errorf "job name %q must be a word (send-welcome, recount_comments) — it becomes the job keyword and the module"
            name))
  (f/check-spec-opts opts)
  (when-let [d (get opts :dir)]
    (unless (empty? (string d)) (f/check-subpath "--dir" d)))
  (def dir (get opts :dir "jobs"))
  (def project (get opts :project "app"))
  {:name base
   :project project
   :plugin (string project "/" base "-job")
   :dir dir
   :module-path (if (empty? dir) base (string dir "/" base))
   :test-dir (get opts :test-dir "test")
   :queue (get opts :queue :default)
   :max-attempts (get opts :max-attempts 5)
   :schedule (get opts :schedule)
   :fields (tuple ;fields)})

(def command
  {:name :make/job
   :doc "Scaffold a background job, its policy and a suite"
   :args ["NAME" "[ARG:TYPE...]"]
   :flags {"--queue" {:key :queue :type :keyword :doc "which queue it runs on (default: :default)"}
           "--max-attempts" {:key :max-attempts :type :int
                             :doc "tries before the dead letter queue (default: 5)"}
           "--schedule" {:key :schedule :doc "a cron spec — adds a defschedule that fires it"}
           "--dir" {:key :dir :doc "where the module lands (default: jobs)"}
           "--test-dir" {:key :test-dir :doc "default: test"}
           "--project" {:key :project :doc "the plugin's namespace (default: this project)"}
           "--force" {:key :force :type :bool :doc "overwrite what is there"}
           "--dry-run" {:key :dry-run :type :bool :doc "print instead of writing"}}})

(defn create
  {:params [{:dir :string? :project :string? :test-dir :string?
             :queue :any :max-attempts :number? :schedule :any
             :dry-run :boolean? :force :boolean? & r}
            :string
            :string]
   :ret [:string]
   :throws [:string]}
  ``The body of `void make job NAME [arg:type ...]`. Returns the tuple
  of paths written — or, under `--dry-run`, the paths it would have
  written.``
  [opts name & field-args]
  (def fields (map f/parse-field field-args))
  (def spec (job-spec name fields
                      (merge {:project (f/project-name)} (table/to-struct opts))))
  (def written (scaffold/run! spec (scaffold/templates entries override-dir) opts))
  (when (opts :dry-run) (break written))
  (print)
  (print "  add to :plugins in main.janet:")
  (print)
  (printf "    :%s%s the job" (spec :plugin)
          (string/repeat " " (max 1 (- 24 (length (spec :plugin))))))
  (print "    :void/jobs                the queue, if it is not there yet")
  (print)
  (print "  then:")
  (print)
  (printf "    void jobs work --queues %s" (string (spec :queue)))
  (print)
  written)
