### void/cli/make/plugin — `void make plugin NAME`.
###
### The whole plugin cycle in one file, which is what a reader has to
### see once before any of the documentation about it means anything: a
### config slice with a schema and defaults, a component that holds
### what the slice configured and is started and stopped by the graph,
### a contribution to somebody else's extension point, a health check,
### and the manifest that ties the four together so that deleting one
### `:plugins` entry removes every trace.
###
### examples/demo is that file, written by hand and read by nobody who
### did not already know where to look. This is the same file, in the
### project that needs it, named after what it is for.

(import ../template)
(import ./spec :as f)
(import ./scaffold)

(def plugin-template
  "The plugin module: config, component, contribution, health, manifest."
  ```
### {{plugin}} — {{title}}.
###
### The whole plugin cycle in one file: a config slice with a schema
### and defaults, a component the graph starts and stops, a
### contribution to an extension point somebody else owns, a health
### check, and the manifest that ties them together. Delete the
### `:{{plugin}}` entry from :plugins in main.janet and every trace of
### this goes with it — that is what a plugin *is* here.
(import void/core/log :as log)
(import void/core/plugin :as plugin)
(import void/core/system :as system)

(def log-ns "{{project}}.{{name}}")

# -- config ---------------------------------------------------------------
#
# The slice is validated at bootstrap phase 2, before anything starts,
# so a typo in config/dev.janet is a boot error with a path in it
# rather than a nil three call frames later.

(def Config
  "Schema of the [:{{name}}] config slice."
  {:enabled [:optional :boolean]
   :greeting [:optional :string]})

(def defaults
  "What the slice means when the application says nothing."
  {:enabled true
   :greeting "hello"})

# -- the component --------------------------------------------------------

(def {{name}}-component
  (system/component :{{name}}/service
    :doc "Holds what the [:{{name}}] slice configured."
    :config {:key :{{name}}}
    :start (fn start [deps cfg]
             (log/info "{{name}} ready" :ns log-ns :greeting (cfg :greeting))
             @{:greeting (cfg :greeting) :served 0})
    :stop (fn stop [inst]
            (put inst :greeting nil))
    :health (fn health [inst]
              {:status (if (inst :greeting) :up :down)
               :served (inst :served)})))

# -- what it does ---------------------------------------------------------

(defn serve
  "The plugin's own work, as an ordinary function of its instance."
  [inst who]
  (put inst :served (inc (inst :served)))
  (string (inst :greeting) ", " who "!"))

# -- a command ------------------------------------------------------------
#
# `:args` and `:flags` are the command's surface as data: void/core/cli
# parses argv against them and renders `void {{name}} greet --help`
# from them, so there is no usage sentence to keep in step by hand.
# `:needs` is the subset of the system this command starts — nothing
# else comes up, and no port is opened.

(plugin/contribute! :void.core/cli
  {:name :{{name}}/greet
   :read-only? true
   :doc "Greet each name"
   :args ["NAME..."]
   :flags {"--loud" {:key :loud :type :bool :doc "shout it"}}
   :needs [:{{name}}/service]
   :fn (fn cli-greet [inst opts & names]
         (each n names
           (def line (serve inst n))
           (print (if (opts :loud) (string/ascii-upper line) line))))})

(plugin/contribute! :void.core/health
  {:name :{{name}}/reachable
   :fn (fn health [] {:status :up})})

# -- the manifest ---------------------------------------------------------

(plugin/defplugin {{plugin}}
  :doc "{{title}}."
  :version "0.1.0"
  :requires {:void/core ">=0.0.1"}
  :config-key :{{name}}
  :config-schema Config
  :config-defaults defaults
  :components [{{name}}-component])
```)

(def test-template
  "The suite: the plugin composes, configures, starts and leaves."
  ```
### {{plugin}} — generated by `void make plugin`.
###
### What a plugin test is for: the composition, not the function. That
### the slice validates, that the component starts under the config the
### slice resolved, that the contribution reaches the point it is
### addressed to, and — the one nobody writes by hand — that dropping
### the plugin leaves nothing behind.
(import void/core/plugin :as plugin)
(import void/core/system :as system)
(import ../{{module-path}} :as {{name}})

(def boot (plugin/start! {:plugins [:{{plugin}}] :profile :test}))

(def inst (get-in boot [:system :instances :{{name}}/service]))
(assert inst "the component started")
(assert (= "hello, Ada!" ({{name}}/serve inst "Ada")) "and does its work")

(def commands (plugin/extension boot :void.core/cli))
(assert (find |(= :{{name}}/greet ($ :name)) commands)
        "the command is contributed under the name `void {{name}} greet` resolves")

(plugin/shutdown! boot)

# the property that makes a plugin a plugin: composed out, nothing
# remains — no component in the graph, no contribution at the point
(def without (plugin/dry-run {:plugins [] :profile :test}))
(assert (empty? (filter |(string/has-prefix? "{{name}}" (string $)) (without :components)))
        "drop it from :plugins and no component of it is left")

(print "{{name}}-plugin-test ok")
```)

(defn- substitutions
  {:params [{:name :string :project :string :plugin :string
             :module-path :string & r}]
   :ret {:name :string :title :string :project :string :plugin :string
         :module-path :string}}
  "The template holes plugin-template and test-template read, built
  from a plugin spec."
  [spec]
  {:name (spec :name)
   :title (f/title (spec :name))
   :project (spec :project)
   :plugin (spec :plugin)
   :module-path (spec :module-path)})

(def entries
  "The two files, and the keys a project's own templates are named after."
  [{:key :plugin
    :path (fn [s] (string (s :module-path) ".janet"))
    :render (fn [s] (template/render plugin-template (substitutions s)))}
   {:key :test
    :path (fn [s] (string (s :test-dir) "/" (s :name) "-plugin-test.janet"))
    :render (fn [s] (template/render test-template (substitutions s)))}])

(def override-dir
  "Where a project keeps its own plugin templates."
  "templates/plugin")

(defn plugin-spec
  {:params [:string (or {:dir :string? :project :string? :test-dir :string? & r} :nil)]
   :ret {:name :string :project :string :plugin :string :dir :string
         :module-path :string :test-dir :string}
   :throws [:string]}
  "The value both templates are a pure function of."
  [name &opt opts]
  (default opts {})
  (def base (f/kebab name))
  (unless (peg/match '(* (range "az") (any (+ (range "az") (range "09") "-")) -1) base)
    (errorf "plugin name %q must be a word (billing, rate-limit) — it becomes the plugin keyword, the config slice and the module"
            name))
  (f/check-spec-opts opts)
  (when-let [d (get opts :dir)]
    (unless (empty? (string d)) (f/check-subpath "--dir" d)))
  (def dir (get opts :dir ""))
  (def project (get opts :project "app"))
  {:name base
   :project project
   :plugin (string project "/" base)
   :dir dir
   :module-path (if (empty? dir) base (string dir "/" base))
   :test-dir (get opts :test-dir "test")})

(def command
  {:name :make/plugin
   :doc "Scaffold a plugin: config, component, contribution, manifest"
   :args ["NAME"]
   :flags {"--dir" {:key :dir :doc "where the module lands (default: beside app.janet)"}
           "--test-dir" {:key :test-dir :doc "default: test"}
           "--project" {:key :project :doc "the plugin's namespace (default: this project)"}
           "--force" {:key :force :type :bool :doc "overwrite what is there"}
           "--dry-run" {:key :dry-run :type :bool :doc "print instead of writing"}}})

(defn create
  {:params [{:dir :string? :project :string? :test-dir :string?
             :dry-run :boolean? :force :boolean? & r}
            :string]
   :ret [:string]
   :throws [:string]}
  ``The body of `void make plugin NAME`. Returns the tuple of paths
  written — or, under `--dry-run`, the paths it would have written.``
  [opts name]
  (def spec (plugin-spec name (merge {:project (f/project-name)}
                                     (table/to-struct opts))))
  (def written (scaffold/run! spec (scaffold/templates entries override-dir) opts))
  (when (opts :dry-run) (break written))
  (print)
  (print "  add to :plugins in main.janet:")
  (print)
  (printf "    :%s" (spec :plugin))
  (print)
  (print "  then:")
  (print)
  (printf "    void %s greet world" (spec :name))
  (print)
  written)
