### void/cli/make/resource — `void make resource NAME field:type ...`.
###
### A resource is one declaration written into four files, and the
### point of generating them together is that they are four projections
### of the same thing: `defentity` is the schema *and* the db-mapping,
### the form markup and its validation are `schema/select` over that
### same node, the routes carry the names the policies will want, and
### the migration creates exactly the columns the entity names. Written
### by hand, those four drift; written from one spec, they cannot — and
### the generated suite checks that they still agree after the first
### edit.

(import ../prompt)
(import ../template)
(import ./spec :as f)
(import ./scaffold)

(defn resource-spec
  {:params [:string
            @[{:name :keyword :type :keyword :optional? :boolean
               :entity :keyword? :rel :keyword? :table :string?}]
            (or {:dir :string? :table :string? :plural :string? :project :string?
                 :migrations-dir :string? :test-dir :string? :version :string? & r}
                :nil)]
   :ret {:name :string :entity :string :plural :string :table :string
         :title :string :project :string :plugin :string :dir :string
         :migrations-dir :string :test-dir :string :version :string
         :fields [{:name :keyword :type :keyword :optional? :boolean
                   :entity :keyword? :rel :keyword? :table :string?}]}
   :throws [:string]}
  ``The value every template is a pure function of:

      {:name "user" :entity "User" :plural "users" :table "users"
       :title "User" :project "demo" :plugin "demo/users"
       :dir "resources" :version "20260830120000" :fields [...]}

  Building it is the whole of the command's judgement; rendering it is
  mechanical, which is why `--dry-run` can show the result without a
  filesystem and why an override only has to be a function of this.``
  [name fields &opt opts]
  (default opts {})
  (def base (f/kebab name))
  # the name becomes a plugin keyword, a table name and a route
  # segment, so it is checked once, here, rather than three times in
  # three error messages nobody wrote
  (unless (peg/match '(* (range "az") (any (+ (range "az") (range "09") "-")) -1) base)
    (errorf "resource name %q must be a word (User, blog-post, BlogPost) — it becomes the plugin %s and the table"
            name (string "<project>/" (f/plural base))))
  (f/check-spec-opts opts)
  (when-let [d (get opts :dir)] (f/check-subpath "--dir" d))
  (def plural-name (or (get opts :plural) (f/plural base)))
  (def project (get opts :project "app"))
  {:name base
   :entity (f/pascal base)
   :plural plural-name
   :table (or (get opts :table) (f/snake plural-name))
   :title (f/title base)
   :project project
   :plugin (string project "/" plural-name)
   :dir (get opts :dir "resources")
   :migrations-dir (get opts :migrations-dir "db/migrations")
   :test-dir (get opts :test-dir "test")
   :version (or (get opts :version) (f/timestamp))
   :fields (tuple ;fields)})

# -- the built-in templates ----------------------------------------------
#
# The holes are filled by ./template, which `void new` uses for the
# same reason: the text of a generated file reads, here, exactly as it
# will read on disk.

(def resource-template
  "The resource module: entity, form projection, views, handlers, routes."
  ```
### {{plugin}} — the {{entity}} resource: entity, views, handlers, routes.
###
### Generated by `void make resource`. Everything below is a projection
### of the one declaration at the top: `db/defentity` is the schema
### *and* the db-mapping, `schema/select` projects the form
### DTO off it instead of repeating it, `form/form` renders that
### projection and `form/submit` validates against it. Rename a field in
### the entity and the form, the validation and the suite follow. The
### migration beside this file is the one thing that does not follow,
### which is why the generated suite compares the two.
###
### Handlers are registered as symbols, so redefining one in the repl —
### or saving this file with `void dev` running — is live.
(import void/core/plugin :as plugin)
(import void/core/schema :as schema)
(import void/db :as db)
(import void/http/router :as router)
(import void/http/ring :as ring)
(import void/html :as html)
(import void/html/form :as form)
(import void/htmx/hx :as hx)

# -- the declaration -----------------------------------------------------

(db/defentity {{entity}}
  {:id [:int {:db/pk true :db/type "integer"}]
   {{schema-fields}}}
  :db/table "{{table}}"{{rels}})

(def {{entity}}Form
  "What the form submits — a projection of the entity, not a copy."
  (schema/select {{entity}} [{{field-keys}}]))

# -- views ---------------------------------------------------------------
#
# Plain functions returning hiccup. `layout` is the resource's own so
# that this file renders the moment it is generated; point it at the
# application's layout and delete this one.

(defn layout [content context]
  (html/html5
    [:head
     [:meta {:charset "utf-8"}]
     [:title "{{plural-title}}"]
     [:script {:src "https://unpkg.com/htmx.org@4.0.0"}]]
    [:body [:main content]]))

(defn {{name}}-form
  ``The create/edit form — one function, because it is one schema. With
  a record it posts an update, without one it posts a create, and on an
  invalid submission the caller hands back the raw values and the
  schema errors and the same markup re-renders annotated.``
  [&opt record values errors]
  (def id (get record :id))
  (form/form {{entity}}Form
    {:action (if id (string "/{{plural}}/" id) "/{{plural}}")
     :values (or values record)
     :errors errors{{form-fields}}
     :submit (if id "Save" "Create")
     # the create route is a :void.htmx/partial, so the create form
     # swaps the fragment in place; the edit form is a plain POST
     :attrs (if id {} (hx/post "/{{plural}}" :target "#{{plural}}"
                               :swap :outer-html))}))

(defn {{plural}}-view
  "The list plus the create form — the fragment htmx swaps."
  [records &opt values errors]
  [:div {:id "{{plural}}"}
   [:h1 "{{plural-title}}"]
   ({{name}}-form nil values errors)
   [:ul {:class "{{plural}}"}
    (if (empty? records)
      [:li {:class "empty"} "Nothing here yet."]
      (seq [r :in records]
        [:li [:a {:href (string "/{{plural}}/" (r :id))}
              (string (get r {{display}} ""))]]))]])

(defn {{name}}-view
  "One record."
  [record]
  [:article
   [:h1 (string (get record {{display}} ""))]
   [:dl
    {{detail-rows}}]
   [:a {:href (string "/{{plural}}/" (record :id) "/edit")} "Edit"]])

# -- handlers ------------------------------------------------------------

(defn- recent
  "The list one page shows."
  []
  (db/query {{entity}} {:order-by [[:id :desc]] :limit 100}))

(defn index
  "GET /{{plural}} — the list and the create form."
  [req]
  (html/page ({{plural}}-view (recent)) {:layout layout}))

(defn new-record
  "GET /{{plural}}/new — an empty form."
  [req]
  (html/page ({{name}}-form) {:layout layout}))

(defn create
  "POST /{{plural}} — validate against the projection, then write."
  [req]
  (form/submit {{entity}}Form (req :form)
    {:ok (fn [v]
           (db/insert! {{entity}} v)
           (html/page ({{plural}}-view (recent)) {:layout layout}))
     :invalid (fn [values errors]
                (html/page ({{plural}}-view (recent) values errors)
                           {:layout layout}))}))

# The record a path names is the route's to say (`:void.db/load` below):
# the id is coerced through the entity's key, and a malformed or
# missing one is a 404 before the handler runs — never a nil that
# reaches a template.

(defn show
  "GET /{{plural}}/:id"
  [req]
  (html/page ({{name}}-view (req :void.db/row)) {:layout layout}))

(defn edit
  "GET /{{plural}}/:id/edit"
  [req]
  (html/page ({{name}}-form (req :void.db/row)) {:layout layout}))

(defn update-record
  "POST /{{plural}}/:id — the same validation as create."
  [req]
  (def record (req :void.db/row))
  (form/submit {{entity}}Form (req :form)
    {:ok (fn [v]
           (db/update! {{entity}} (record :id) v)
           (ring/redirect (string "/{{plural}}/" (record :id))))
     :invalid (fn [values errors]
                (html/page ({{name}}-form record values errors)
                           {:layout layout}))}))

(defn destroy
  "POST /{{plural}}/:id/delete"
  [req]
  (db/delete! {{entity}} ((req :void.db/row) :id))
  (ring/redirect "/{{plural}}"))

# -- routes --------------------------------------------------------------
#
# A literal segment has to be declared before `:id` swallows it, so
# /new keeps its place above /:id. The route names are written out
# because they are also the policy names void/authz and void/admin ask
# about — one name, read by three things.

(router/defroutes :{{project}}/{{plural}}-routes
  (GET "/{{plural}}" index {:name :{{plural}}/index})
  (GET "/{{plural}}/new" new-record {:name :{{plural}}/new})
  (POST "/{{plural}}" create {:name :{{plural}}/create
                             :void.htmx/partial true})
  (GET "/{{plural}}/:id" show {:name :{{plural}}/show
                               :void.db/load {:entity {{entity}}}})
  (GET "/{{plural}}/:id/edit" edit {:name :{{plural}}/edit
                                    :void.db/load {:entity {{entity}}}})
  (POST "/{{plural}}/:id" update-record {:name :{{plural}}/update
                                         :void.db/load {:entity {{entity}}}})
  (POST "/{{plural}}/:id/delete" destroy {:name :{{plural}}/destroy
                                          :void.db/load {:entity {{entity}}}}))

(plugin/defplugin {{plugin}}
  :doc "{{title}} resource: entity, form, CRUD routes."
  :version "0.1.0"
  :requires {:void/http ">=0.0.1" :void/html ">=0.0.1"
             :void/htmx ">=0.0.1" :void/db ">=0.0.1"
             :void/db-http ">=0.0.1"})
```)

(def migration-template
  "The migration that creates the table the entity names."
  ```
### {{table}} — generated by `void make resource {{name}}`.
###
### What a step returns is executed: void/db/builder compiles the
### statement map for whichever engine is running, which is what keeps
### one migration file portable. Apply it with `void db migrate`.
(defn up []
  {:create-table "{{table}}"
   :columns [[:id :serial {:primary-key true}]
             {{columns}}]})

(defn down []
  {:drop-table "{{table}}"})
```)

(def test-template
  "The suite: the declarations still agree."
  ```
### The {{entity}} resource — generated by `void make resource`.
###
### Not one of these checks needs a database, and that is the point.
### They are about the *declarations* agreeing, which is the mistake
### this file's neighbours actually make: the entity, the form schema
### and the routes are three projections of one declaration, so a field
### renamed in one and not in the others fails here. The migration is
### the one thing that is not a projection — it is a separate file that
### created the columns — so it is read back as data and compared
### column by column.
###
### The CRUD path itself wants a driver in :plugins and `void db
### migrate` applied; void/test's inject then drives the
### routes without opening a socket.
(import void/core/plugin :as plugin)
(import void/core/schema :as schema)
(import void/db :as db)
(import ../{{dir}}/{{plural}} :as resource)

# -- the form schema is a projection of the entity ------------------------

(def valid
  "One record satisfying every field the entity declares."
  {{sample}})

(def checked (schema/check resource/{{entity}}Form valid))
(assert (empty? (checked :errors))
        (string "a valid {{name}} passes: " (string/format "%q" (checked :errors))))
{{empty-check}}
# -- the entity and the migration name the same columns -------------------

(def desc (db/resolve-entity resource/{{entity}}))
(def migration (dofile "{{migration-path}}"))
(def created
  (map |(db/snake (first $))
       (get ((get-in migration ['up :value])) :columns)))

(assert (= "{{table}}" (desc :table))
        "the entity and the migration agree on the table name")
(each c (desc :columns)
  (assert (index-of c created)
          (string "column " c " is declared by the entity but never created")))

# -- the routes are declared, under the names a policy asks about ---------

(def declared
  (get-in plugin/manifest-registry
          [:{{plugin}} :contributes :void.http/route-source 0 :routes :children]))
(def names (map |(get-in $ [:meta :name]) declared))

(each name [{{route-names}}]
  (assert (index-of name names) (string "route " name " is declared")))

(print "{{plural}}-test ok")
```)

(def empty-check-template
  "The half of the suite that only exists when a field is required."
  ```

(def empty-check (schema/check resource/{{entity}}Form {}))
(assert (not (empty? (empty-check :errors)))
        "an empty submission is refused by the schema, not by a handler")

```)

(defn- migration-path
  {:params [{:migrations-dir :string :version :string :table :string & r}]
   :ret :string}
  "Where the migration this spec describes lives, built the same way
  from a fresh spec or one read back off disk."
  [spec]
  (string (spec :migrations-dir) "/" (spec :version)
          "_create_" (spec :table) ".janet"))

(defn- substitutions
  {:params [{:name :string :entity :string :plural :string :table :string
             :title :string :project :string :plugin :string :dir :string
             :migrations-dir :string :test-dir :string :version :string
             :fields [{:name :keyword :type :keyword :optional? :boolean
                       :entity :keyword? :rel :keyword? :table :string?}]
             & r}]
   :ret {:name :string :entity :string :plural :string :table :string
         :title :string :plural-title :string :plugin :string :project :string
         :dir :string :version :string :migration-path :string :field-keys :string
         :display :string :sample :string :schema-fields :string :columns :string
         :rels :string :form-fields :string :detail-rows :string :route-names :string}
   :throws [:string]}
  "Every hole the built-in templates have, filled from the spec. An
  override that wants one of them gets it by calling this."
  [spec]
  (def disp (f/display-field spec))
  (def ff (f/form-fields spec))
  (def rs (f/rels spec))
  {:name (spec :name)
   :entity (spec :entity)
   :plural (spec :plural)
   :table (spec :table)
   :title (spec :title)
   :plural-title (f/title (spec :plural))
   :plugin (spec :plugin)
   :project (spec :project)
   :dir (spec :dir)
   :version (spec :version)
   :migration-path (migration-path spec)
   :field-keys (f/field-keys spec)
   :display (string/format "%q" (disp :name))
   :sample (string "{" (f/sample-source spec) "}")
   :schema-fields
   (f/indent 3 (map |(string/format "%q %s" ($ :name) (f/node-source $)) (spec :fields)))
   :columns (f/indent 13 (map f/column-source (spec :fields)))
   :rels
   (if (empty? rs)
     ""
     (string "\n  :db/rels {"
             (f/indent 12 (map |(string/format "%q [:belongs-to %q %q]"
                                             ($ :rel) ($ :entity) ($ :name))
                             rs))
             "}"))
   :form-fields
   (if (empty? ff) "" (string "\n     :fields {" (f/indent 14 ff) "}"))
   :detail-rows
   (f/indent 4 (map |(string/format "[:dt %q] [:dd (string (get record %q \"\"))]"
                                  (f/title (string ($ :name))) ($ :name))
                  (spec :fields)))
   :route-names
   (string/join (map |(string/format ":%s/%s" (spec :plural) $)
                     ["index" "new" "create" "show" "edit" "update" "destroy"])
                "\n            ")})

(defn- render-resource
  {:params [{:name :string :entity :string :plural :string :table :string
             :title :string :project :string :plugin :string :dir :string
             :migrations-dir :string :test-dir :string :version :string
             :fields [{:name :keyword :type :keyword :optional? :boolean
                       :entity :keyword? :rel :keyword? :table :string?}]
             & r}]
   :ret :string
   :throws [:string]}
  "The resource module, rendered for this spec."
  [spec]
  (template/render resource-template (substitutions spec)))

(defn- render-migration
  {:params [{:name :string :entity :string :plural :string :table :string
             :title :string :project :string :plugin :string :dir :string
             :migrations-dir :string :test-dir :string :version :string
             :fields [{:name :keyword :type :keyword :optional? :boolean
                       :entity :keyword? :rel :keyword? :table :string?}]
             & r}]
   :ret :string
   :throws [:string]}
  "The migration that creates the table this spec's entity names,
  rendered for this spec."
  [spec]
  (template/render migration-template (substitutions spec)))

(defn- render-test
  {:params [{:name :string :entity :string :plural :string :table :string
             :title :string :project :string :plugin :string :dir :string
             :migrations-dir :string :test-dir :string :version :string
             :fields [{:name :keyword :type :keyword :optional? :boolean
                       :entity :keyword? :rel :keyword? :table :string?}]
             & r}]
   :ret :string
   :throws [:string]}
  "The suite that checks the entity, the form and the migration still
  agree, rendered for this spec."
  [spec]
  (def subs (substitutions spec))
  (template/render
    test-template
    (merge subs
           {:empty-check
            (if (every? (map |($ :optional?) (spec :fields)))
              ""
              (template/fill empty-check-template subs))})))

(def override-dir
  "Where a project keeps its own resource templates."
  "templates/resource")

(def template
  ``The built-in resource template, as data: one entry per file, each
  with the `:key` a project override is named after, a `:path` and a
  pure `:render`. Nothing here touches the filesystem — `scaffold/run!`
  does.``
  [{:key :resource
    :path (fn [s] (string (s :dir) "/" (s :plural) ".janet"))
    :render render-resource}
   {:key :migration
    :path migration-path
    :render render-migration}
   {:key :test
    :path (fn [s] (string (s :test-dir) "/" (s :plural) "-test.janet"))
    :render render-test}])

# -- interactive ---------------------------------------------------------

(defn- ask-fields
  {:params []
   :ret @[{:name :keyword :type :keyword :optional? :boolean
           :entity :keyword? :rel :keyword? :table :string?}]
   :throws [:string]}
  ``The interactive pass: fields, one at a time, until an empty name.
  It only runs when no field was given on the command line and there is
  a terminal to run it on — `void make resource User name:string` is
  the same command without the conversation.``
  []
  (def out @[])
  (print)
  (print "  Fields, one per line. An empty name finishes.")
  (print)
  (forever
    (def name (prompt/ask "  field name" {:default ""}))
    (when (empty? name) (break))
    (def type (prompt/choose "  type" f/field-types {:default :string}))
    (def entity
      (when (= :ref type)
        (prompt/ask "  belongs to which entity" {:default "User"})))
    (def optional? (prompt/confirm "  may it be empty?" false))
    (array/push out
                (f/parse-field
                  (string name ":" (string type)
                          (if entity (string ":" entity) "")
                          (if optional? "?" "")))))
  out)

# -- create --------------------------------------------------------------

(def command
  ``What `void make resource` takes, as the same declaration every
  other void command carries: void/core/cli parses argv against it and
  renders its `--help`.``
  {:name :make/resource
   :doc "Scaffold entity + routes + views + migration + tests"
   :args ["NAME" "[FIELD:TYPE...]"]
   :flags {"--table" {:key :table :doc "table name (the pluralizer is a guess)"}
           "--plural" {:key :plural :doc "plural of NAME"}
           "--dir" {:key :dir :doc "where the module lands (default: resources)"}
           "--migrations-dir" {:key :migrations-dir :doc "default: db/migrations"}
           "--test-dir" {:key :test-dir :doc "default: test"}
           "--project" {:key :project :doc "the plugin's namespace (default: this project)"}
           "--version" {:key :version :doc "the migration's version, for a reproducible run"}
           "--force" {:key :force :type :bool :doc "overwrite what is there"}
           "--dry-run" {:key :dry-run :type :bool :doc "print instead of writing"}
           "--no-input" {:key :no-input :type :bool :doc "never ask, even on a terminal"}}})

(defn create
  {:params [{:no-input :boolean? :dir :string? :table :string? :plural :string?
             :project :string? :migrations-dir :string? :test-dir :string?
             :version :string? :dry-run :boolean? :force :boolean? & r}
            :string
            :string]
   :ret [:string]
   :throws [:string]}
  ``The body of `void make resource NAME [field:type ...]`: the fields
  from the command line or, when there are none and there is a terminal
  to ask on, from the interactive pass.

  Returns the tuple of paths written — or, under `--dry-run`, the paths
  it would have written.``
  [opts name & field-args]
  # the conversation happens only when there is nothing to have it
  # about and somebody to have it with
  (def fields (map f/parse-field field-args))
  (def all-fields
    (if (and (empty? fields) (not (opts :no-input)) (prompt/interactive?))
      (ask-fields)
      fields))
  (when (empty? all-fields)
    (error "a resource with no fields is a table with no columns — pass name:type arguments"))
  (def spec-opts (merge {:project (f/project-name)} (table/to-struct opts)))
  (def spec (scaffold/specced
              |(resource-spec name all-fields (merge spec-opts $))
              opts))
  (def written (scaffold/run! spec (scaffold/templates template override-dir) opts))
  (when (opts :dry-run) (break written))

  # what is *not* done, said in full: `make` writes new files and edits
  # none, so the composition it needs is printed rather than assumed. A
  # resource is the first thing in a fresh project that needs the
  # entity layer and a driver at all.
  (print)
  (print "  add to :plugins in main.janet:")
  (print)
  (printf "    :%s%s the routes, the entity and the views"
          (spec :plugin) (string/repeat " " (max 1 (- 24 (length (spec :plugin))))))
  (print "    :void/db :void/db-sqlite  the entity layer and a driver, if not there yet")
  (print "    :void/db-http             the row loader the routes' :void.db/load needs")
  (print "                              (its module is void/db/http — import it in main.janet,")
  (print "                              which is what registers the keyword)")
  (print)
  (print "  then:")
  (print)
  (print "    void db migrate")
  (printf "    void dev                 # /%s" (spec :plural))
  (print)
  written)
